### ISSUE TITLE
Raster proxies generated in a .csv file different to proxies generated as individual .mrf files

### ISSUE THREAD

**Issue by alexkemp94** [Esri/OptimizeRasters#100]
Hi,

I am trying to generate raster proxies for a set of images stored in Microsoft Azure blob storage in a .csv format, using the CreateRasterProxy.xml template. This is so that I can embed the proxies in a mosaic dataset instead of having a path that references a folder of individual .mrf proxies.

![image](https://user-images.githubusercontent.com/33670839/76399924-6382dc80-6377-11ea-925e-66509f6fc0aa.png)

I have been able to generate the .csv file populated with the relevant raster proxies but have found that the proxies cannot be read in ArcGIS Pro. I have compared the output proxies in the .csv to a set of proxies generated for the same set of images but as individual .mrf files (which can be read in Pro) and have found that the output proxies in the .csv are different. The two images below show two raster proxies for the same image - the first generated as an individual .mrf file and the second generated in a .csv file (and then formatted for comparison).

![image](https://user-images.githubusercontent.com/33670839/76400568-6fbb6980-6378-11ea-88a6-473501e36f59.png)
![image](https://user-images.githubusercontent.com/33670839/76400591-76e27780-6378-11ea-9a6a-d81c6a9b3c58.png)

It appears that the compression type changes from JPEG (which it should be) to LERC when creating the proxies in a .csv file, as well as the PageSize parameter, the Rsets model tag and some other elements of the xml.

Please let me know if you need any more information or a copy of the data.

Alex

**Comment by Chamlika** [comment]
@alexkemp94 Let's have a look with the latest code updated on GitHub, and if you still face issues, let me know. Thanks!

**Comment by alexkemp94** [comment]
Hi @Chamlika, this has now been resolved. Thank you.
