### ISSUE TITLE
RasterProxies don't generate in .CSV when cloud to local

### ISSUE THREAD

**Issue by ahzarkie** [Esri/OptimizeRasters#101]
Hi, i'm trying to create raster proxies on images that are currently held in azure blob storage (in MRF format). I'm trying to make local proxies in CSV format using the OptimizeRasters toolbox. I'm using the 'CreateRasterProxy' config file and only changing the exclude filter to no longer contain aux_xml.

When I run the tool it says it runs successfully:
![OR_params-image](https://user-images.githubusercontent.com/29734934/77549820-37537980-6ea8-11ea-8e74-3d9fb50e7843.png)

However, it is creating no proxies in the CSV (sorry the date is wrong on this as I removed some of the header lines due to rerunnning a few times):
![OR_csv](https://user-images.githubusercontent.com/29734934/77549929-5eaa4680-6ea8-11ea-9aa0-55f9929571f1.PNG)

and making local proxies for the aux_xml files (which was removed from the exclude filter)
![OR_output](https://user-images.githubusercontent.com/29734934/77549974-6e298f80-6ea8-11ea-8c29-cdeb3f87ed25.png)

Local to local works fine, and azure to local when not using a CSV also works as intended.
This issue doe not seem linked to my PC as asked others to run, resulting in the same issue.

If you need any more info let me know :)

**Comment by Chamlika** [comment]
@ahzarkie Please let me know if you still face issues with the latest code updated. Thanks!

**Comment by abhiataero** [comment]
@ahzarkie  did you get a chance to try it out

**Comment by ahzarkie** [comment]
@Chamlika @abhiataero Hi both, sorry only just got round to running this - When I now run cloud to local with the updated code, the csv is being populated with  image proxies, and the aux_xml files are being generated as individual files next to the CSV as expected. Thank you :)
