### ISSUE TITLE
Method to generate rasterproxy-csv file for Sentinel2 data?

### ISSUE THREAD

**Issue by gauteaasolaas** [Esri/OptimizeRasters#102]
The Sentinel2 MS dataset is a multiband product with diverse extra files with metadata. It seems like embedding proxies for this kind of data is not supported, or is there a way around the issues?
With Kubernetes the deployment of thousands of proxy-files fails. What about loading binary tar-files or 7z-files into the raster-column to support this?

**Comment by gauteaasolaas** [comment]
I've tried both with and without specifying  -inputprofile Sentinel2_to_MRF_Ireland.xml with the exact same result.
I've been tipped that the tool MDTools with a product definition from 
https://github.com/Esri/raster-types/tree/master/types
should do the trick. It should replace the rasterdef in the Mosaic Dataset directly. However, I haven't been able to make it work on my setup just yet.

D:\work\GAMP_workspace_ia9ef3269\RUN1234567_workspace_sentinel>c:\Python27\ArcGISx6410.7\python.exe OptimizeRasters201911\OptimizeRasters.py -mode rasterproxy -input D:\servicedata\Sentinel2\mrfproxy\3871 -output D:\work\GAMP_workspace_ia9ef3269\RUN1234567_workspace_sentinel\sentinelorbit_3871.csv -subs true -cache /mrftemp/sentinel2/3871 > rasterpwxy_sentinel2_without_inputprofile.log

[rasterpwxy_sentinel2_without_inputprofile.log](https://github.com/Esri/OptimizeRasters/files/4538066/rasterpwxy_sentinel2_without_inputprofile.log)

**Comment by abhiataero** [comment]
@gauteaasolaas  in teh template can you add jp2 as a raster format then run, currently jp2 is not part of it, that is the reason it does not create any raster proxy.

**Comment by gauteaasolaas** [comment]
Ah. That was more like it! 
I had used the wrong keyword for the template-file: -inputprofile instead of -config
Now the csv-file looks perfect!
TY :)
D:\work\GAMP_workspace_ia9ef3269\RUN1234567_workspace_sentinel>c:\Python27\ArcGISx6410.7\python.exe OptimizeRasters201911\OptimizeRasters.py -input D:\servicedata\Sentinel2\mrfproxy\3871 -output D:\work\GAMP_workspace_ia9ef3269\RUN1234567_workspace_sentinel\sentinelorbit_3871_allproducts.csv -mode rasterproxy -config D:\work\GAMP_workspace_ia9ef3269\RUN1234567_workspace_sentinel\OptimizeRasters201911\UserTemplates\Sentinel2_to_rasterproxy_Ireland.xml -subs true -cache /mrftemp/sentinel2/3871/0c779d0c-69e6-4e01-9d3d-21766ca38ae01 > sentinel2_rasterproxy_success.log

[sentinel2_rasterproxy_success.log](https://github.com/Esri/OptimizeRasters/files/4538935/sentinel2_rasterproxy_success.log)

**Comment by gauteaasolaas** [comment]
Not so perfect after all. The bands of each produt came in as separate rows instead of a composite Sentinel2 product.
This is a typical name-column-content for a Sentinel2 product when MRF-encoding with OptimizeRasters:
raster_footprints; OID=1;raster_footprints; OID=2;raster_footprints; OID=3;raster_footprints; OID=4;raster_footprints; OID=5;raster_footprints; OID=6;raster_footprints; OID=7;raster_footprints; OID=8;
The same bands now will be loaded each in one row.

**Comment by gauteaasolaas** [comment]
MDTools did the trick after-all. I just had to get the call right.
So heres the recipe: Install MDTools
Fix paths to proxies in the MD.
Run command line e.g. like this:
A:\mdtools>"C:\Program Files (x86)\ArcGIS\Desktop10.7\bin\mdtools.exe" --md=A:\mdtools\MosaicDataset.gdb\s_3870_MS --embedrasterproxy
I believe this is the right tool for this exercise, so I opt to close this task again.
