### ISSUE TITLE
Support for Azure v5.0 sdk

### ISSUE THREAD

**Issue by RandallRebello** [Esri/OptimizeRasters#103]
Update the documentation on how to install Azure. Changes have been made in April 9 2020. 
Refer to https://pypi.org/project/azure/

Suggest we make a batch file and include it as part of OptimizeRasters . 
the instructions for batch file use would be to copy it to the python\scripts folder and run from there.

**Comment by Chamlika** [comment]
@RandallRebello @abhiataero MSFT has broken the function prototypes for the azure.storage module. This will create issues with the clients that need to install latest azure modules. 
The solution is to upgrade OptmizeRasters to use the azure.storage.blob==12.3.0+

**Comment by blairdgeo** [comment]
I second this request.  I noticed that in both ArcMap and ArcGIS Pro that I am no longer able to export rasters to Azure.

**Comment by Chamlika** [comment]
Note> azure.storage.blob is the only requirement to use MSFT azure with OptimizeRasters.
i.e.  pip3 install azure.storage.blob
