### ISSUE TITLE
local to blob will not create aux.xml even when removed from excluded filter

### ISSUE THREAD

**Issue by csnd1** [Esri/OptimizeRasters#104]
Hi there, when uploading from local to blob I'm trying to create aux.xml files alongside populating the chosen csv. However, even when removed from the excluded config filter, I am being left with only the populated csv, and no accompanying aux.xml files. With this all the correct files are uploaded to blob.

![image](https://user-images.githubusercontent.com/55745515/80393393-5464d900-88a8-11ea-9e79-360300a0e8ad.png)

![image](https://user-images.githubusercontent.com/55745515/80393104-f0421500-88a7-11ea-8e31-d06ba454e0f4.png)

When running the CreateRasterProxy from blob back to local, I am able to generate both a populated CSV and aux.xml files, and so I was wondering why both could not be generated in the local to blob step highlighted above? 

if you need to know anything else please let me know!

Thanks :)

**Comment by Chamlika** [comment]
@csnd1 Available with the next release, the aux.xml files will always be copied to the the (Raster Proxy Output Folder) that points to a .CSV file.
