### ISSUE TITLE
'The specified module could not be found' error

### ISSUE THREAD

**Issue by KazzaS** [Esri/OptimizeRasters#105]
Hi,

Today I downloaded the newest OR version of 2020-09-21, but when running the 'Overviews_to_MRF_JPEG.xml' template I get the following error:

log-msg:...: The specified module could not be found.
log-msg:ERROR 1: Can't load requested DLL: C:\Image_Mgmt_Workflows\OptimizeRasters\GDAL\bin\gdalplugins\gdal_MG4Lidar.dll

The C:\Image_Mgmt_Workflows\OptimizeRasters\GDAL\bin\gdalplugins\gdal_MG4Lidar.dll does exist.

Could you please fix this error?

Thanks,
Karin

**Comment by abhiataero** [comment]
@KazzaS  can you confirm that the below folder exists 
C:\Image_Mgmt_Workflows\OptimizeRasters\GDAL\bin\gdalplugins

**Comment by Chamlika** [comment]
@KazzaS Can you re/install the MSFT VC+ runtime 2015-2019 and check, thanks!
https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by KazzaS** [comment]
Thank you, Chamlika, that worked. I installed it on the EC2 instance which is a Windows Server 2016 machine.  Also running the OR CreateRasterProxy.xml in rasterproxy mode, the local proxy directory does not get created, I get the error:"log-critical:[Errno 2] No such file or directory:". Again, this is only on the Windows Server 2016 machine.
Thank you very much :-)

**Comment by Chamlika** [comment]
@KazzaS  Good to hear! I'll have a look at the proxy folder issue as well. Thank you!

**Comment by kstronkh** [comment]
Hi Chamlike, we are still experiencing that the rasterproxy folder needs to exist before running the Imagery_to_MRF_LERC template in OR.  Was this fixed?
Thank you,
Karin

**Comment by Chamlika** [comment]
@kstronkh Are you using the UI?

**Comment by kstronkh** [comment]
Hi Chamlike, no we're using CommandLine.

**Comment by Chamlika** [comment]
@kstronkh Can you change the local proxy directory to 2 levels deep like c:/mydata/proxyfiles/ and have a look? This could be related to creating a folder at the drive root on the Windows Server 2016 machine that you're on. Also if you can, please pass me the cmd-line used to see if I can recreate the issue here. Thanks!

**Comment by kstronkh** [comment]
Hi Chamlika,
The needing of the proxy folder in place before running the latest version of OR occurs on any of our computers, not only on the Windows Server 2016.
The levels at which we create the proxies is as follows and until now we never had issues:
C:\....\....\.....\.....\mrf_proxy
Thanks you,
Karin
