### ISSUE TITLE
Fails to Create a RasterProxy for Sentinel2 COG

### ISSUE THREAD

**Issue by stev-0** [Esri/OptimizeRasters#109]
I am able to convert OpenAerialMap COGs fine, but there seems to be a problem with the [Sentinel-2 data on AWS](https://registry.opendata.aws/sentinel-2-l2a-cogs/). I wonder if this is because it also has a STAC catalogue.

For instance, with the following parameters I am unable to get the tool to create a raster proxy:
```
Configuration File: CreateRasterProxy
Input Source: Amazon S3
Input Profile: Public Bucket
Input Bucket Container: sentinel-cogs
Input Bucket: sentinel-s2-l2a-cogs/2019/S2B_28RGU_20191209_0_L2A/B08.tif (note I also tried with the B08.tif omitted)
Output Destination: Local
Output Path: <my path>
```

Result is:

```
log-msg:Done..
log-status:[Failed!]
```

Parameters for successful COG:
```
Configuration File: CreateRasterProxy
Input Source: Amazon S3
Input Profile: Public Bucket
Input Bucket Container: oin-hotosm
Input Bucket: 5faff8ddf5b34900056e78a7/0
Output Destination: Local
Output Path: <my path>
```

In any case, some more documentation about how to connect to these rich resources would be very welcome - COGs are getting quite popular these days!

**Comment by Chamlika** [comment]
@stev-0 There's seems to be a limitation with the UI/Profile Editor. The UI is not able to set the region where the bucket is located when creating a new profile.
For now, I'd suggest having the below entry manually added into the **%USERPROFILE%\.aws\credentials** file to continue with your work using either the OptimizeRasters UI or the console.

**[public]
region=us-west-2**

Once added, you can select the profile added (public) on the OptimizeRasters UI or at the console using the following command,
python OptimizeRasters.py -input sentinel-s2-l2a-cogs/2019/S2B_28RGU_20191209_0_L2A -clouddownload true -config c:\Image_Mgmt_Workflows\OptimizeRasters\Templates\CreateRasterProxy.xml -inputbucket sentinel-cogs -output outputPath -inputprofile **public**

**Comment by stev-0** [comment]
OK, thanks, bit of a delay but got this to work. Only through the cli though, not the GUI for some reason.
