### ISSUE TITLE
Linux Install

### ISSUE THREAD

**Issue by niwacolours** [Esri/OptimizeRasters#110]
We would like to run OptimizeRasters on our supercomputer, in a Linux environment. How does that get installed and configured?

I've successfully used it for 'manual' conversion of large volumes of NetCDF (nc) files to MRF, including LERC compression, using an install and the command line on my Windows PC. Here, I use a Python2.7 which came with my ArcMap.
 
The installation instructions provide a link to an .exe installer and nothing for Linux, although, under the Requirements section, it says that it can be used on Linux. How?

There is the "Lambda" function installer available under https://github.com/Esri/OptimizeRasters/blob/master/Setup/Lambda/OptimizeRastersLambdaFX.zip - would I be using the contents of this zip file? is it as easy as unzipping it on my Linux target and scheduling the process to run with my configuration?

 
Thank you for any help on this -

 

Tilmann

**Comment by Chamlika** [comment]
@niwacolours I could provide an OR docker image, will that make things easier on your side?

**Comment by niwacolours** [comment]
Thanks Chamlika,

That would be a great solution! What other ways are there to install it on Linux? Is that documented somewhere?

Tilmann

**Comment by Chamlika** [comment]
@niwacolours There's a slim version of OR Linux setup made available for you to download and test. The setup link/info at https://github.com/Esri/OptimizeRasters/blob/master/Setup/Linux/readme-info.txt

**Comment by niwacolours** [comment]
That's very helpful - thanks a lot for sending that through Chamlika!

Cheers,
Tilmann
