### ISSUE TITLE
Tiff LZW template says to use Deflate, not LZW

### ISSUE THREAD

**Issue by maphew** [Esri/OptimizeRasters#112]
https://github.com/Esri/OptimizeRasters/blob/3a39f4e18e8f2e95db9a66eb4c4ff3c5234711a3/Templates/Imagery_to_TIF_LZW.xml#L15
https://github.com/Esri/OptimizeRasters/blob/3a39f4e18e8f2e95db9a66eb4c4ff3c5234711a3/Templates/Imagery_to_TIF_LZW.xml#L30

**Comment by abhiataero** [comment]
fix has been made
