### ISSUE TITLE
Help Documentation - imRoleURL [Defaults] url mixup

### ISSUE THREAD

**Issue by esriau-rlangford** [Esri/OptimizeRasters#113]
Hey, 

we received an email from a client who found that when reviewing the help for the OptimizeRasters tools > ProfileEditor tool the imRoleURL endpoints are mixed up (see attached screenshot)

imRoleURL (Optional)
Dialog Reference
.....
[Defaults]
Amazon S3 = http://blob.core.windows.net
Microsoft Azure = http://s3.amazonaws.com
![OptimizeRastersToolsHelp](https://user-images.githubusercontent.com/80432530/110722422-ee820580-825d-11eb-9519-0d8ff6c6652f.jpg)

**Comment by abhiataero** [comment]
@Chamlika  can you make the update
