### ISSUE TITLE
handling rotation in tiffs

### ISSUE THREAD

**Issue by elwoodhouse** [Esri/OptimizeRasters#114]
I was wondering if someone could check that I've not overlooked a setting somewhere as when I run the Imagery_to_MRF_JPEG template my resultant MRF files do not preserve the rotation in the source tif image.
Source image on bottom with rotation, MRF on top:
![image](https://user-images.githubusercontent.com/38488541/110734383-d0c39900-827b-11eb-9f60-a73f63079207.png)

I thought this might have been due to GDAL needing a world file so I created world files with the Export Raster World File GP tool and put them in the source directory and the input temp folder but that didn't make a difference.

Does anyone know where I should be looking to fix this or is this a limitation of the OptimizeRaster/ArcGIS toolset?

**Comment by lucianpls** [comment]
It's an MRF limitation, rotation and skew are not allowed. The workaround is to reproject the source to eliminate the rotation.
