### ISSUE TITLE
IAM role access - expired token

### ISSUE THREAD

**Issue by elwoodhouse** [Esri/OptimizeRasters#121]
I was wondering if anyone else has seen the behavior we are getting when running longer jobs that upload to S3?

We are converting from tif to MRF as the first step in our OptimizeRaster job and using an IAM Role to provide access to a private S3 bucket. The script runs fine and uploads files to the output S3 bucket until the temporary credentials assigned to the IAM role (currently set to the default 6 hour expiry) expire. After that time, all S3-Push commands get an error of:

(Failed to upload ...LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml to .../LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.) - 2

I believe we can extend the temporary credentials expiry for the IAM role up to 12 hours, but this isn't going to be long enough to complete our larger processing jobs.

I've looked through the OptimizeRaster code and I don't see any mechanism where it refreshed credentials if they expire. Is what we are experiencing a limitation of using IAM Role credentials with the current implementation? To work around we have changes to the aws credentials file.

This is an extract of the log file of the last successful push, and first unsuccessful push:
`NFO:root:**[S3-Push] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756243_54_0001_0001.pjg - 0
INFO:root:**[Del] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756242_54_0001_0001.pjg - 0
INFO:root:**[Del] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756242_54_0001_0001.mrf - 0
INFO:root:**[Del] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756242_54_0001_0001.idx - 0
INFO:root:**Status: (OK). - 0
INFO:root:**Applying compression ("/gisdata/image_processing_temp/tmp9qdvbk6g/rasters_in/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.tif") - 0
INFO:root:**262144 / 17362320  (1.51%) - 0
INFO:root:**524288 / 17362320  (3.02%) - 0
INFO:root:**17100176 / 17362320  (98.49%) - 0
INFO:root:**17362320 / 17362320  (100.00%) - 0
INFO:root:**[S3-Push] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756243_54_0001_0001.mrf.aux.xml - 0
INFO:root:**222 / 222  (100.00%) - 0
INFO:root:**[Del] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756243_54_0001_0001.idx - 0
INFO:root:**[Del] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756243_54_0001_0001.mrf - 0
INFO:root:**[Del] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756243_54_0001_0001.pjg - 0
INFO:root:**[Del] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756243_54_0001_0001.mrf.aux.xml - 0
INFO:root:**Orjob/Snapshot/Status>True@2021-05-19 08:10:58.842834 - 0
INFO:root:**Status: (OK). - 0
INFO:root:**Applying compression ("/gisdata/image_processing_temp/tmp9qdvbk6g/rasters_in/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.tif") - 0
INFO:root:**messages: - 0
INFO:root:**b'Input file size is 5000, 5000' - 0
INFO:root:**b'0...10...20...30...40...50...60...70...80...90...100 - done.' - 0
INFO:root:**Status: (OK). - 0
INFO:root:**Creating pyramid ("/gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf") - 0
INFO:root:**Using GDALInfo ("/gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf").. - 0
INFO:root:**<PyramidFactor> set to (2 4 8 16) - 0
INFO:root:**messages: - 0
INFO:root:**b'Input file size is 5000, 5000' - 0
INFO:root:**b'0...10...20...30...40...50...60...70...80...90...100 - done.' - 0
INFO:root:**Status: (OK). - 0
INFO:root:**Creating pyramid ("/gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf") - 0
INFO:root:**Using GDALInfo ("/gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf").. - 0
INFO:root:**<PyramidFactor> set to (2 4 8 16) - 0
INFO:root:**Status: (OK). - 0
INFO:root:**[Amazon-Push].. - 0
INFO:root:**[S3-Push] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml - 0
INFO:root:**(Failed to upload /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml to arcgis-imagery/MRF/LowerDarling2013_20cm_all/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.) - 2
INFO:root:**Status: (OK). - 0
INFO:root:**[Amazon-Push].. - 0
INFO:root:**[S3-Push] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf - 0
INFO:root:**(Failed to upload /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf to arcgis-imagery/MRF/LowerDarling2013_20cm_all/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.) - 2
INFO:root:**[S3-Push] (MRF/LowerDarling2013_20cm_all/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml), retries-left (2) - 1
INFO:root:**[S3-Push] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml - 0
INFO:root:**(Failed to upload /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml to arcgis-imagery/MRF/LowerDarling2013_20cm_all/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.) - 2
INFO:root:**[S3-Push] (MRF/LowerDarling2013_20cm_all/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf), retries-left (2) - 1
INFO:root:**[S3-Push] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf - 0
INFO:root:**(Failed to upload /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf to arcgis-imagery/MRF/LowerDarling2013_20cm_all/LowerDarling2013-RGB-0_2_5756245_54_0001_0001.mrf: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.) - 2
INFO:root:**[S3-Push] (MRF/LowerDarling2013_20cm_all/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml), retries-left (1) - 1
INFO:root:**[S3-Push] /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml - 0
INFO:root:**(Failed to upload /gisdata/image_processing_temp/tmp9qdvbk6g/rasters_out/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml to arcgis-imagery/MRF/LowerDarling2013_20cm_all/LowerDarling2013-RGB-0_2_5756244_54_0001_0001.mrf.aux.xml: An error occurred (ExpiredToken) when calling the PutObject operation: The provided token has expired.) - 2`

**Comment by Chamlika** [comment]
@elwoodhouse You're right, the (temporary) credentials for the IAM Role instance do not get refreshed before the expiry time. The issue will be addressed to implement the support for workflows that need to work over many hours/days. For now, I'd suggest to split the larger jobs with many rasters that could possibly take more than 12 hours to upload into smaller batches until we've a fix.

**Comment by Chamlika** [comment]
Let me know if you face any further issues, thanks!
