### ISSUE TITLE
Updating to GDAL 3.x?

### ISSUE THREAD

**Issue by maphew** [Esri/OptimizeRasters#124]
Are there specific reasons Optimize Rasters is using GDAL 2.3 and not the 3.x series? Are there things the community might be able to work on to help transition?

I'd like colleagues to take advantage of the ZSTD compression available in gdal v3, and the built in COG driver is an added convenience. For my own use I'm happy enough with my commandline gdal scripts that do this but my compatriots are more comfortable using toolboxes.

**Comment by Chamlika** [comment]
@maphew Thank you for reaching out to us. 
Yes, GDAL v3+ updates will be available on the next release. COG conversion templates to use the built-in GDAL driver.
