### ISSUE TITLE
Error during OR run 25/05/21 relating to GDAL DLL change?

### ISSUE THREAD

**Issue by sandrews90208** [Esri/OptimizeRasters#126]
<Message>warnings/errors:</Message>
		<Message>ERROR 1: Can't load requested DLL: C:\Image_Mgmt_Workflows\OptimizeRasters\GDAL\bin\gdalplugins\gdal_MG4Lidar.dll</Message>
		<Message>126: The specified module could not be found.</Message>

The error seems to suggest an issue with one of the GDAL binaries which from looking at the github page were updated back in March. 
When investigating I tried installing a fresh new copy of OR onto the server but got the same errors but additional ones complaining about a second GDAL binary file:

I tried running OR through Arc Pro to confirm the error and it also failed with the same error. I noticed the compressed files are written into the output temp directory even though the error is reported.

As a workaround I tried removing the two offending dll files and that seems to fix it.

Given that we automate the installation of OR as part of our ArcGIS Server deployment, if we do an automated reinstall, the problem will likely recur as those binaries are in the github repo.

**Comment by Chamlika** [comment]
@sandrews90208 Thank you for reporting, could you tell me the OR template used.

**Comment by sandrews90208** [comment]
hi chamlika, its a customised version of the overviews_to_mrf_jpeg template. i can email over a copy if that helps?

**Comment by Chamlika** [comment]
@sandrews90208  Hi, could you test with the next release candidate to see if your issue gets resolved, this isn't yet on GitHub but will be in the next few days, thanks!
https://esriis-my.sharepoint.com/:u:/g/personal/cham4757_esri_com/EeKiLLBzulBAvz4YFaS7mb4BjvKZokWwm8Yg5wWrO9CaJg?e=hh3Phc
