### ISSUE TITLE
Document rasterproxy file format

### ISSUE THREAD

**Issue by drwelby** [Esri/OptimizeRasters#129]
It appears the rasterproxy file format shares a similar format to the MRF metadata file, but could you share a schema or some example files to compare against?

**Comment by abhiataero** [comment]
@drwelby  Raster proxy and MRF have same structure, there are two major difference 

1. The raster proxy has a source node which points to the location of the source data 
2. The raster proxy has data and index node which tell you the location where the data will be stored locally for caching 

The Raster proxy is called as Caching MRF if it is pointing to  any raster other than MRF 
The Raster proxy is called as Clone MRF if it is pointing to MRF raster format 

more information on this can be found in this link 

https://github.com/nasa-gibs/mrf/blob/master/doc/MUG.md

**Comment by drwelby** [comment]
Thanks for the clarification, using the Caching MRF as a starting point I was able to generate working Raster Proxies with GDAL.
