### ISSUE TITLE
 CleanMRFCache.py documentation is not inline with the code

### ISSUE THREAD

**Issue by benjaminturrell** [Esri/OptimizeRasters#130]
In the clean MRF cache tool on the arguement for size says that the input should be in Bytes. 

On line 159:
space_to_free = args.size * 1000000000

This suggests that the input size should be in GB as line 159 then calculates it out into Bytes. 

This is causing the cache to delete all the files and the script is highly likely to respond with "Unable to Free space requested" 

Can the documentation please be updated to change from bytes to gigabytes as the input?

**Comment by Chamlika** [comment]
@benjaminturrell  Thanks for pointing out, the doc has been updated.
FYI @abhiataero
