### ISSUE TITLE
Python Package Manager of ArcGIS Pro 2.9 does not provide azure packages

### ISSUE THREAD

**Issue by rasgithub** [Esri/OptimizeRasters#136]
Tryed to install the azure python package as described in the doc (page 4), but no 'azure' package will be provided.
![image](https://user-images.githubusercontent.com/45854242/144050116-d5224019-86d3-4755-b49d-e1be0b955340.png)
Can I use Azure-common instead?

**Comment by rasgithub** [comment]
Same issue with 2.8

**Comment by Chamlika** [comment]
Fixed on Pro 3.2.2, we now have the following azure entries in the Package Manager. 
azure-core
azure-storage-blob
@rasgithub
