### ISSUE TITLE
S3 Files >2GB Cause OverflowError Due to SSL

### ISSUE THREAD

**Issue by mbeaucha** [Esri/OptimizeRasters#138]
Attempting to use OR on an S3-hosted image larger than 2GB triggers an overflow/'signed int greater than max value' error in python versions prior to 3.10 as the underlying SSL library is limited to 32-bit reads. Solution changes reading of file from S3 to be done via iterator over large chunks that stay below the 32-bit limit, rather than trying to read all in one call.

Please see pull-request of the same name that corrects this issue.

**Comment by Chamlika** [comment]
@mbeaucha Thanks for finding out the issue. The code was not supposed to read the entire file into memory unless it was an MRF which is text and quite small in size. Looks like the original code/intention was broken and overlooked during an earlier code upgrade process. This will be corrected in a follow up, thank you!
@abhiataero

**Comment by Chamlika** [comment]
@mbeaucha I've updated the OptimizeRasters.py for the fixes, however the Setup/OptimizeRastersToolsSetup.exe will take few hours to update. You can fetch just the updated source file to see if everything looks good with your tests/needs.
Thanks!

**Comment by mbeaucha** [comment]
Thank you very much! I will pull the latest and check it out!

**Comment by Chamlika** [comment]
@mbeaucha  Please pull only the https://github.com/Esri/OptimizeRasters/blob/master/OptimizeRasters.py directly, the setup is not yet updated, thanks!
