### ISSUE TITLE
Create raster proxy with CSV output target fails when input on S3

### ISSUE THREAD

**Issue by mbeaucha** [Esri/OptimizeRasters#141]
These seems to be the same as prior issue #101 which occurred with input in Azure, but my input is in S3 and it still does not work. The CSV file created is empty other than the header.  When the input is moved to local disk and run with the same config file it works fine, CSV is populated. The input in question is a valid MRF file, despite the error message produced by OR:

log-msg:[Resume] Creating job (/OptimizeRasters-master/OR_20220208T211448557712.orjob)
log-msg:[S3-Pull] ./imagename.mrf.aux.xml
log-msg:[S3-Pull] ./imagename.nitf.aux.xml
log-msg:
Processing caching operations...
log-critical:Updating (./imagename.mrf) was not successful!
Please make sure the input is (MRF) format.
[Errno 2] No such file or directory: './imagename.mrf'
log-critical:Updating (./imagename.mrf) was not successful!

**Comment by Chamlika** [comment]
@mbeaucha The fixes have been added to GitHub binary setup/source. You can have a look and let us know, thanks!
