### ISSUE TITLE
Incorrect external raster proxies being generated

### ISSUE THREAD

**Issue by younggrr** [Esri/OptimizeRasters#142]
- Using "OptimizeRasters" with "CreateRasterProxy" configuration.
- Source files are 32-bit single band MRF with LERC compression in Azure blob storage (4,908 tiles total). 
- Output is a local folder
- Result after loading into mosaic dataset is swiss cheese:

![image](https://user-images.githubusercontent.com/11195930/155355583-06efd566-3abd-45ca-9e1c-bfc49dc43a57.png)

- Also tiles are being placed in the wrong location:

![image](https://user-images.githubusercontent.com/11195930/155355948-8ab0f561-2553-44b3-a3ef-e0230ffd8882.png)

- Examination of proxy files shows a mismatch between the source tile name and the \<DataFile> and \<IndexFile>names.  The proxy is referencing the wrong data:

![image](https://user-images.githubusercontent.com/11195930/155357647-824faf6e-c335-4509-b276-93d11eb80dc6.png)

- If I try creating as proxy table instead (ie csv output) it works as expected.  Unfortunately we cannot use embedded proxies at this time.

What's causing this to occur?

**Comment by Chamlika** [comment]
@myoung1000  Can you confirm you still have this issue, thanks!

**Comment by myoung1000** [comment]
@Chamlika - I believe you want to ask a different young...

**Comment by Chamlika** [comment]
> @Chamlika - I believe you want to ask a different young...

oops, yes. 

Thanks!

**Comment by Chamlika** [comment]
@younggrr Can you confirm you still have this issue, thanks!

FYI @abhiataero

**Comment by younggrr** [comment]
@Chamlika I tried on a test dataset and I believe the problem has been resolved. Will re-open this if the problem reappears.
