### ISSUE TITLE
Logged message in cloudwatch logs

### ISSUE THREAD

**Issue by gbadanahatti** [Esri/OptimizeRasters#143]
Using OptimizeRasters Lambda. I see the following in the cloudwatch logs. Although, I see the output written in my S3 bucket, I am trying to understand the implications of the following error message is to the processing.

log-msg: /tmp/gdaladdo: /var/task/GDAL/bin/libcurl.so.4: no version information available (required by /var/task/GDAL/bin/libgdal.so.20)

**Comment by Chamlika** [comment]
@gbadanahatti  Please ignore the harmless warning message, curl isn’t involved with any image processing. If you see the output as expected, it’s all fine. Thanks!
