### ISSUE TITLE
Clarification on Commit Comment "GDAL v3.0.0+ with built-in COG support..."

### ISSUE THREAD

**Issue by bixb0012** [Esri/OptimizeRasters#145]
The Commit comment from @Chamlika on Jul, 13, 2021 states:
> GDAL v3.0.0+ with built-in COG support plus fixes/enhancements

The comment is straightforward enough, but what I am trying to understand is how that comment reconciles with the fact that EXEs under `OptimizeRasters/GDAL/bin/` all show file version 2.3.3.98.  I will admit I am not a regular GDAL user, but how does 2.3.3.98 equal 'v3.0.0+' ?

Apologies if I am missing the obvious.

**Comment by Chamlika** [comment]
@bixb0012  These OR GDAL binaries built from public GDAL source carry internal versioning that do not match to public GDAL version numbers and can have fixes/enhancements.
@abhiataero

**Comment by bixb0012** [comment]
@Chamlika, thanks for the reply and clarification, it definitely helps.  Determining/finding the public GDAL version numbers is simple enough, is there a way users can find the OR GDAL internal version from files installed on their machine.  

*I realize comments in GH give me an answer, or at least an idea of an answer, but I am looking for something that can be done with files already installed on local machine.*

**Comment by bixb0012** [comment]
I understand that Pro is already using GDAL 3.x code.  For example with Pro 2.9.2, the GDAL DLLs show a version of 3.3.0.25, and you just stated that will increment to 3.4.x with Pro 3.0.

Maybe my context confused the matter more than clarified it because I really am just focused on trying to understand versioning within compiled GDAL files with OptimizeRasters and not any other Esri products.  Given all the GDAL DLLs under `OptimizeRasters/GDAL/bin/gdalplugins/` show a version of 2.3.3.98, I am trying to figure out how an OR user would know that a bunch of upstream 3.x code is compiled in those DLLs by looking at the files installed by `OptimizeRastersToolsSetup.exe`.

**Comment by Chamlika** [comment]
@bixb0012  Windows GDAL builders have come back saying it'd be best to look at the (features) that are available with the OR released GDAL binaries than to compare with the version number reported. At least for now, the version numbers are never in sync with the publicly released versions.
