### ISSUE TITLE
Clarification on what Windows installer does (to set paths)

### ISSUE THREAD

**Issue by ZoltanKelly** [Esri/OptimizeRasters#146]
Hi, working in a locked down Windows corporate environment without installing permissions is makes it challenging to manage an install of OptimizeRasters (as exe requires admin approval, and subsequent versions).
What does the Windows installer actually do vs. running the toolbox direct from the zipped download? viewing config files after running the installer, it doesn't seem to update any references to a root path, and there's nothing added as user or system variables visible environment variables.
i.e. if it's unzipped somewhere other than the default C:\Imagery_Mgmt_Workflows\OptimizeRasters, it possible to 'simulate' the installer behaviour by setting the root path in one of the config files manually, or is it adding registry keys or similar?

**Comment by Chamlika** [comment]
@ZoltanKelly You can download the GitHub repo as a zip and have unzipped manually to C:\Imagery_Mgmt_Workflows\OptimizeRasters\ and start off from there.
The OR setup (EXE) was added only for convenience for few users.

**Comment by ZoltanKelly** [comment]
Thanks, yes I think I worked out my issue. If I added it to pro, then moved the folder and tried to run it again from the new location, it was still using the initial folder location paths and throwing 'GDAL is not found' errors in logs.
Closing and reopening Pro resolved the issue, I think because of some caching function in Pro. Thanks! You can close this.
