### ISSUE TITLE
mrf files not uploaded to aws S3 when using -rasterproxypath (lrc, xml, idx do upload)

### ISSUE THREAD

**Issue by james-swiftgeo** [Esri/OptimizeRasters#149]
I am using CLI to create an as standard as possible command to achieve the following:
- convert TIFFs in a folder to mrf
- push mrf and associated files to an S3 bucket
- simultaneously create a local proxy file
I can do the conversion and push the resultant files to the aws S3 bucket using a slightly modified Imagery_to_MRF_LERC config. When I repeat the command and only add -rasterproxypath and a local path, the proxy is created and the the tiffs are converted successfully (the mrf is in the temp folder, but deleted after uploads), but only the associated files are pushed to the bucket (lrc, xml, idx) - not the mrf files.
At the same time a .mrf.aux.xml file is created for each TIFF in the folder where the config is located.
Thanks

**Comment by lucianpls** [comment]
It's likely because collocated .mrf files are not needed when proxy files exist. The content of the proxy file and the .mrf file is more or less the same. You should be able to generate the collocated .mrf content from the proxy content, if you want both, by removing the DataFile and IndexFile tags.

**Comment by james-swiftgeo** [comment]
Thanks for the prompt response. I see what you are saying that the mrf is essentially the same as the proxy, however I don't want to attempt to extract multiple mrf's from a single proxy csv, that would be very tricky and prone to errors. My workflow is to take a folder of multiple TIFFS, run optomise rasters in mrf mode with -rasterproxypath pointing to a single csv, have it convert to mrf and push them to an S3 bucket. Then on a separate enterprise machine I add the single proxy (that contains proxys for multiple mrfs stored in S3) to a mosaic dataset. Form the documentation I was under the impression that this would be a very common workflow - is there a better way of accomplishing this? In an older version of optomise rasters I had this working, but for some reason in this newer one the mrfs now don't make it to the bucket. Everything else appears to work as before.
