### ISSUE TITLE
Is webp supported for converting from tiff to mrf

### ISSUE THREAD

**Issue by BoudewijnBoogaard** [Esri/OptimizeRasters#150]
I have downloaded a tiff image that is apparently compressed using webp. If I try to convert this tiff to mrf using OptimizeRasters I get the following error message:

"Cannot open TIFF file due to missing codec"

Does anyone know if this compression method is supported or can be supported?

It looks like ArcGIS Pro 3.x is the first version of ArcGIS Pro that supports this compression type. I wasn't able to add these images to versions prior to ArcGIS Pro 3.x.

I've attached a sample image to this post.

**Comment by Chamlika** [comment]
@BoudewijnBoogaard  We'll have the MRF/WEBP compression added into the next release, thansk!

**Comment by lucianpls** [comment]
You mean TIFF/WEBP, right?

**Comment by Chamlika** [comment]
> You mean TIFF/WEBP, right?
> 
> 

oops, yes @lucianpls 
Thanks for pointing out.

**Comment by BoudewijnBoogaard** [comment]
> 

You are right. We are receiving Tiff/Webp and I'm not able to convert to to MRF/LERC.

Will this be on the road map?
