### ISSUE TITLE
up-to-date Linux setup file

### ISSUE THREAD

**Issue by azinsharaf** [Esri/OptimizeRasters#151]
hi, Is there any plan to provide Linux setup file? The existing one is for 2021.

**Comment by Chamlika** [comment]
@azinsharaf Will have Linux setup upgraded to the latest OR source + GDAL binaries, thanks!

**Comment by Chamlika** [comment]
@azinsharaf The Linux setup has been updated to the latest OR source. The GDAL version however remains the same, but will be upgraded to GDAL 3..3.3 in due course.

Linux setup @ 
https://esriis-my.sharepoint.com/personal/cham4757_esri_com/_layouts/15/onedrive.aspx?ga=1&id=%2Fpersonal%2Fcham4757%5Fesri%5Fcom%2FDocuments%2Fesri%2FOptimizeRasters%2FLinux

For setup info, please refer to the readme-info.txt at the same cloud location. 

FYI @abhiataero

**Comment by azinsharaf** [comment]
Thanks. I check it out.
