### ISSUE TITLE
Problem converting WV3 to MRF

### ISSUE THREAD

**Issue by gmorlock** [Esri/OptimizeRasters#24]
I installed OptimizeRasters yesterday and have been experimenting with converting WorldView-3 imagery to MRF.  I started by trying to use OptomizeRasters to convert and upload the MRF files to S3.  The process seemed to work but when I checked the files on S3 they were very small -- just a few bytes.  They obviously didn't convert.  I didn't check the log file to see if there were errors.

I decided to pull back and try something simpler.  I just used the DG template to convert to MRF on the local file system (I made a minor modification to the xml to create more pyramids up to a factor of 1024).  The scrypt seemed to complete successfully but after looking, I saw errors I don't understand (I do understand the pyramid level warnings).

I tried to access the .imd files in the output MRF folder using ArcMap.  ArcMap warned me that the images had inconsistent spatial references.  I checked, and the ntf files, which I understand are now MRF, did not had a spatial reference.  I tried to manually add a reference using ArcCatalog.  It did not take.

I have attached the log file from OptimizeRasters.

Greg Morlock
[OptimizeRastersLog.txt](https://github.com/Esri/OptimizeRasters/files/169694/OptimizeRastersLog.txt)

**Comment by PBecker92373** [comment]
Greg
Let us take a look at this.
I believe this is something related to how GDAL_Translate handles NITF files. A preliminary review of this shows that the RPCs are being lost.

The pyramid level warnings are just to define that you have defined pyramids that are smaller than 1 tile so will not be created. It is better to define too many pyramids and get some warnings back then have too few and end up with gaps. I’m hoping in a future version we can remove the warnings or just create the correct levels.

_Peter

**Comment by gmorlock** [comment]
OK, thanks.  I look forward to hearing from you.

Greg

**Comment by gmorlock** [comment]
Peter,
After our conversation this morning, just checking on the status of this problem.

**Comment by PBecker92373** [comment]
The existing version does loose the RPC information from the NITF files. A fix is going into OptimizeRasters to correct this but it does require and update to the GDAL part so will take a bit more time. There is also a requirement to get ArcGIS to pick up the RPCs correctly from the Aux.xml files which should be in the next 10.4.1 release.

**Comment by gmorlock** [comment]
OK, Thanks.

**Comment by abhiataero** [comment]
The issue has been fixed
