### ISSUE TITLE
Validate the Credentials

### ISSUE THREAD

**Issue by abhiataero** [Esri/OptimizeRasters#25]
In the profile Tool when the user enters the credentials, there should be an option to validate them

**Comment by Chamlika** [comment]
Let me look into this, I believe the functionality (To validate/List bucket names/e.t.c) should be exposed by OptimizeRasters.py through a UI interface. Will write code.

**Comment by Chamlika** [comment]
UI Enhancements added> 
1. New user credentials get validated at the time of creation.
2. input/output bucket list automatically gets populated to reflect the available bucket/container names connected with the chosen input/output profile.
