### ISSUE TITLE
Temp output should be disable if the mode is Clone/Cache MRF and output storage is local

### ISSUE THREAD

**Issue by abhiataero** [Esri/OptimizeRasters#26]
Temp output should be disable if the mode is Clone/Cache MRF and output storage is local

Other issue is 
If the user is using clone/cache MRF mode and defined temptoutput the MRF file should be generated in the output folder and not tempoutputfolder

**Comment by Chamlika** [comment]
-tempoutput will not be disabled but now should function properly by moving the files in the -tempoutput to -output location. Code being tested.
