### ISSUE TITLE
Creation of MRF from Service Overview hangs

### ISSUE THREAD

**Issue by rdunn3** [Esri/OptimizeRasters#28]
I'm trying to create MRF files from Service Overviews using the Overviews_to_MRF_LERC template. The process hangs at the first file. I don't see gdal_translate in Task Manager either. 

This may be a permissions issue since I don't have admin rights on this machine.

Executing: OptimizeRasters Overviews_to_MRF_LERC Local Profile Local G:\workspace\MosaicDatasets\test # Local Profile Local G:\workspace\MosaicDatasets\OptimizeRasterOvrConversion # # # # "Mode mrf;RasterFormatFilter tif,tiff,TIF,TIFF,img,jp2,JP2,IMG;ExcludeFilter tmp,rrd,idx,lrc,mrf_cache,pjp,ppng,pft,pzp,ovr,aux.xml,aux,tfw,TFW,pjg;Compression LERC;Quality #;LERCPrecision #;BuildPyramids false;PyramidFactor '2 4 8 16 32 64';PyramidSampling avg;PyramidCompression LERC;NoDataValue #;BlockSize 512;Scale #;KeepExtension false;Threads 4"
Start Time: Thu Apr 14 11:32:06 2016
Running script OptimizeRasters...
log-msg: Copying non rasters/aux files (G:/workspace/MosaicDatasets/test/=>G:/workspace/MosaicDatasets/OptimizeRasterOvrConversion/)..
log-msg: Done.
log-msg: Converting..
log-msg: [Resume] Creating job (C:\Image_Mgmt_Workflows\OptimizeRasters\OR_20160414T113206660000.orjob)
log-msg: Copying non rasters/aux files (G:/workspace/MosaicDatasets/test/=>G:/workspace/MosaicDatasets/OptimizeRasterOvrConversion/)..
log-msg: CPY Ov_i04_L01_R00000BF9_C00000443.tif.msk
log-msg: CPY Ov_i04_L01_R00000BF9_C00000444.tif.msk
log-msg: CPY Ov_i04_L01_R00000BF9_C00000445.tif.msk
log-msg: CPY Ov_i04_L02_R000005FB_C00000221.tif.msk
log-msg: CPY Ov_i04_L02_R000005FB_C00000222.tif.msk
log-msg: CPY Ov_i04_L02_R000005FC_C00000221.tif.msk
log-msg: CPY Ov_i04_L02_R000005FC_C00000222.tif.msk
log-msg: CPY Ov_i04_L03_R000002FD_C00000110.tif.msk
log-msg: CPY Ov_i04_L03_R000002FD_C00000111.tif.msk
log-msg: CPY Ov_i04_L03_R000002FE_C00000110.tif.msk
log-msg: CPY Ov_i04_L03_R000002FE_C00000111.tif.msk
log-msg: CPY Ov_i04_L04_R0000017E_C00000088.tif.msk
log-msg: CPY Ov_i04_L04_R0000017F_C00000088.tif.msk
log-msg: CPY Ov_i04_L05_R000000BF_C00000044.tif.msk
log-msg: CPY Ov_i04_L06_R0000005F_C00000022.tif.msk
log-msg: CPY Ov_i04_L07_R0000002F_C00000011.tif.msk
log-msg: Done.
log-msg: Converting..
log-msg: [Thread-1] Applying compression (G:/workspace/MosaicDatasets/test/Ov_i04_L01_R00000BF7_C00000443.tif)

**Comment by Chamlika** [comment]
I heard you got the workflow working successfully via a MS-DOS window. Will see what's going on when the UI is used. However, I believe this is an isolated incident.

**Comment by rdunn3** [comment]
Did you try reproducing this as a user that does not have admin privileges?

**Comment by Chamlika** [comment]
Roslyn,
    I'll still have to do and test that. Will let you know.

-Chamlika

Sent from my Windows Phone
________________________________

**Comment by rdunn3** [comment]
I have verified that this is not an issue with OptimizeRasters. It happened because the Azure python libraries weren't properly installed (because the install user did not have admin privs on the machine).
