### ISSUE TITLE
CloneMRF of Service Overview files don't display at all scales

### ISSUE THREAD

**Issue by rdunn3** [Esri/OptimizeRasters#29]
I'm using CloneMRF to create reference copies of my Service Overviews in Azure Blob storage. 

The mrf still has a reference to pyramids even though I set buildpyramids to false:

  <Rsets model="uniform" scale="2"/>

The result is that the service overview won’t display at all scales because it thinks it has a pyramid.

**Comment by Chamlika** [comment]
The latest update should clear this issue. Please update with just the OptimizeRasters.py or the setup on GitHub and have a look. Thanks.
