### ISSUE TITLE
Optimizing 16 bit data

### ISSUE THREAD

**Issue by Petwet2000** [Esri/OptimizeRasters#30]
I am working with a large amount of 16 bit satellite imagery data. I ran into some obstacles when I tried to use OptimizeRaster “Imagery_to_TIF_JPEG” config file to optimize the images. My questions are as follows:
1.  Is there a template that would allow users to rescale 16bit to 11bit and also handle 4 band and single band imagery?  
2.  Optimize raster seems to build internal overviews by default. It would be good to have an option in the “Advanced” section to switch to “external overviews.”

**Comment by gsumerling** [comment]
Hello, I came across the same issue with multiband image sets. The solution is to use the JPEG Band Interleave compression method. I have attached the sample XML that I used for this and a script below:

C:\PYTHON27\ArcGISx6410.4\python.exe C:\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py -config=c:\Image_Mgmt_Workflows\OptimizeRasters\Templates\Multibandcompressed_to_MRF_JPEG.xml -input=E:\data\imagery\Mosaic_Feature_extract\image_source -output=E:\data\optimise_rasters\outputimage -mode=mrf

Regards
Gordon

[Multibandcompressed_to_MRF_JPEG.zip](https://github.com/Esri/OptimizeRasters/files/226983/Multibandcompressed_to_MRF_JPEG.zip)

**Comment by Chamlika** [comment]
Please note on the usage to support external pyramids>

Using a parameter file,
    <BuildPyramids>external</BuildPyramids>

Using the cmd-line equivalent,
      -pyramids=external 

Using the UI,
	Advanced->Edit configuration values
	Set the (buildPyramids) parameter to 'external'

Note the following conditions that would enable the external pyramid support. 
if the Compression is either 'jpeg' or 'png' AND the <mode> is NOT 'mrf' related.

**Comment by Petwet2000** [comment]
Thank you Chamlika. I will try this.

Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>

**Comment by Petwet2000** [comment]
Hi Gordon,

Thanks for the info and the script. I will review and try it.

Cheers,

**Comment by Chamlika** [comment]
@Petwet2000  Did you get over this issue?

**Comment by Petwet2000** [comment]
Hi,
Apologizes for the delayed response. I was out of office for two weeks. I just tried using a 3 band 16 bit and got the following:

log-msg: warnings/errors:
log-msg: Warning 6: TIFFTAG_MAXSAMPLEVALUE metadata item is unhandled and will not be written
log-msg: Warning 6: TIFFTAG_MINSAMPLEVALUE metadata item is unhandled and will not be written
log-msg: ERROR 1: JPEGSetupEncode:BitsPerSample 16 not allowed for JPEG
log-msg: ERROR 1: WriteEncodedTile/Strip() failed.
log-msg: ERROR 1: JPEGSetupEncode:BitsPerSample 16 not allowed for JPEG
log-msg: ERROR 1: WriteEncodedTile/Strip() failed.
log-msg: ERROR 1: JPEGSetupEncode:BitsPerSample 16 not allowed for JPEG
log-msg: ERROR 1: WriteEncodedTile/Strip() failed.
log-msg: ERROR 1: D:/Temp/2017/Ras_Optimize3band/17MAR24082214-S2AS_R1C1-056242936010_01_P001.tif, band 1: An error occured while writing a dirty block
log-msg: ERROR 1: D:/Temp/2017/Ras_Optimize3band/17MAR24082214-S2AS_R1C1-056242936010_01_P001.tif, band 2: An error occured while writing a dirty block
log-msg: ERROR 1: D:/Temp/2017/Ras_Optimize3band/17MAR24082214-S2AS_R1C1-056242936010_01_P001.tif, band 3: An error occured while writing a dirty block
log-msg: ERROR 1: JPEGSetupEncode:BitsPerSample 16 not allowed for JPEG
log-msg: ERROR 1: WriteEncodedTile/Strip() failed.
log-msg: Status: (FAILED).
log-msg: Done..


Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>

**Comment by Petwet2000** [comment]
Hi Chamlika,

I hope this mail finds you well. Is there are way presently to optimize 16bit 4 band imagery using JPG compression?

Thanks,

Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>

**Comment by lucianpls** [comment]
It is a format limitation, JPEG supports 8 or 12 bits per pixel, not 16.
For 16 bit, LERC should work fine.  For higher compression ratio, use a LERC max error of 1 or 2, it will be slightly lossy at that point, similar to JPEG.

**Comment by PBecker92373** [comment]
Note that there is an advanced option in OptimizeRasters that enables GDAL Parameters to be added.
The explanation includes the following
GDAL_Translate_UserParameters : User GDAL_Translate values. These values will be passed on without any modification. Refer to http://www.gdal.org/gdal_translate.html for more options.
Examples: (Refer to the link above for full explainations.)
•	-scale 200 255 0 255 (Rescale the input pixels values)
•	-outsize 10% 10% (Set the size of the output file)
•	-Scale 0 65536 1 25 (scale from 16 to 8bit and leave 0)
•	-b 1 -b 2 -b 3 (Extract 3 bands)
•	-co NBITS=8 (Output should be 8bits)
•	-ot Byte (Set output to byte)
IE If your data is 16bit and uses the complete 0-65535 data range the you can include the following to reduce it to 0 - 4096 and then if JPEG is used as the compression option it will be compressed using 12bit JPEG. This will scale the data to a suitable data range for 12bit compression
	-Scale 0 65536 1 4096 -co NBITS=16 -ot UInt16
(The -co NBITS and -ot may not be required if the input is already 16bit int)

**Comment by Petwet2000** [comment]
Hi Lucian,

Thanks for this.

Cheers,

Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>
