### ISSUE TITLE
Input Bucket/Container and/or Output Bucket/Container Required for Local Source/Destination

### ISSUE THREAD

**Issue by gmorlock** [Esri/OptimizeRasters#32]
When filling out the OptimizeRasters form if using a local source, the Input Bucket/Container is required and throws an exception when trying to execute.  Likewise if you specify a local destination, the Output Bucket/Container is required and throws and exception.

**Comment by Chamlika** [comment]
Thanks for reporting. A fix has been added to (OptimizeRasters.pyt).
You can either download just the OptimizeRasters.pyt or the OptimizeRastersToolsSetup.exe off the GitHub.
