### ISSUE TITLE
Problem using Imagery_to_MRF_LERC from S3 to S3

### ISSUE THREAD

**Issue by gmorlock** [Esri/OptimizeRasters#34]
I am using version 20160503 of OptimizeRasters.  I copied several GB worth of imagery from my local server to a S3 bucket using DragonDisk.  I then tried using OptimizeRasters with the Imagery_to_MRF_LERC process to convert the S3 imagery to MRF in another S3 bucket.  The process fails saying that access is denied on the source files.  I have verified that all can read from the bucket.  The log and orjob files are attached.
[OptimizeRasterLog_5-4-16.zip](https://github.com/Esri/OptimizeRasters/files/249469/OptimizeRasterLog_5-4-16.zip)

**Comment by Chamlika** [comment]
@gmorlock I've no issues using/processing the .orjob file attached. Could you double check to see if it was a temporary S3 access issue.

**Comment by gmorlock** [comment]
I just tried it again.  It still fails with the same errors.  Could it be
the version of Python -- 2.7.10?  I updated boto to 2.40.0 to make sure and
ran again.  Same errors.

Greg
