### ISSUE TITLE
Tool runs (kind of) but MRF seems empty

### ISSUE THREAD

**Issue by cjgabris** [Esri/OptimizeRasters#35]
I am dealing with many DG Images that take up massive amounts of storage. I want to be able to use the OptimizeRaster tool to store the images in an s3 bucket, and use the MRF files locally in a mosaic dataset and eventually publish as an Image Service.

The tool runs for about an hour, and then fails. However, I am seeing a MRF file in my Clone directory, as well as files in the cache, temp and s3 directories. But when I open the MRF in ArcMap it is empty and has no spatial reference.

Has anyone else encountered something similar?

![optimizeraster](https://cloud.githubusercontent.com/assets/8806479/17251299/1b11552a-5576-11e6-8d7c-a31d59f3dc96.jpg)

**Comment by rdunn3** [comment]
I've been using this tool for a limited time, but this is my understanding. I always run the tool twice. First I would run the tool with the DG_SatelliteProduct_to_MRF_LERC template, but you don't need those last 3 arguments yet (just specify the output destination, output profile, output bucket, and the output path). This will convert your tiff to mrf in S3.

Next you will run the tool with the CloneMRF template. Point to your S3 bucket as input, and the output path will now be on a local drive. The (clone) mrf files created in the output path are much smaller in size, as internally they are just xml files which point back to the "real" mrf files in S3. Don't forget to also specify a cache folder as well. You may need to create a directory structure within the cache folder which mirrors your input, as some files may have the same name. The cache folder is often placed on an ephemeral drive, as it is expendable, and can be easily replaced. In fact, you will need to delete the cache periodically using the CleanMRFCache.py script in the installation directory.

I hope this helps.

**Comment by cjgabris** [comment]
@rdunn3 thank you for this feedback. I tried to run the tool with the limited parameters and found that my data was not copied to s3.

In my old workflow, I am able to get results back from s3, add the TIFs to a mosaic dataset and publish as an image service. The tool does throw an error though, and I am not sure if it is problematic to what I am trying to do. 
![optimizeraster](https://cloud.githubusercontent.com/assets/8806479/17262082/66f35a34-55a7-11e6-9e62-b90ba95022d1.jpg)

**Comment by Chamlika** [comment]
@cjgabris The error shows the file conversion went through successfully but the failure happened while marking its progress in the log file. From your response it sounds like you got the workflow working OK and was able to serve the image service. If possible, see if you could send the .xml log/orjob file on this particular workflow found in the OptimizeRasters (log) folder and send it across as a zipped attachment with your GitHub response to help look into this further.

**Comment by cjgabris** [comment]
@Chamlika Have posted the log files here. I am still looking for the optimum/best practice workflow based on what the tool offers and what I am ultimately trying to do (display many DG images from s3 MRF files as an Image Service). I am currently taking all the output MRF .TIF files in my Clone folder for a particular image and adding them to a mosaic dataset. I am 
![optimizeraster2](https://cloud.githubusercontent.com/assets/8806479/17309583/91b6e5e8-580d-11e6-9477-c6e5be7faec2.jpg)
building pyramids (some which are failing, looking into that now) and merging into one file. I want to be able to do that for many DG images in one mosaic.
[Logs_Cjgabris.zip](https://github.com/Esri/OptimizeRasters/files/394788/Logs_Cjgabris.zip)

**Comment by CodyBenkelman** [comment]
Chris - I can't answer at the technical depth that Chamlika can, but your comment about building pyramids isn't clear to me.  Do you mean "as part of OptimizeRasters" (before building MD)?  I don't think you'll want to use ArcMap to create Pyramids of MRF format rasters in an MD.  The rasters should have pyramids within the MRF format and S3 storage.  Once in the MD, you may want to build Overviews (not Pyramids) but that will depend on how many datasets you have in same area w/ different dates.  

If you need further info on Pyramids vs. Overviews, let me know.

Cody B.

**Comment by gsumerling** [comment]
Hello Chris,

The black images look like the pyramids have not all been created correctly. In the .xml template file you need to set the BuildPyramids to true, but in the PyramidFactor set it as: <PyramidFactor></PyramidFactor>. This forces an autocalculate on the pyramids. Also if your using multiband DG imagery then I suggest using the interleave option as BAND. This then provides the optimal compression for greater than 3 bandimages

Cheers
Gordon

**Comment by cjgabris** [comment]
@CodyBenkelman Thanks for responding Cody! My workflow has been to run OptimizeRasters on a DG Image, build pyramids on the output files in the Clone folder, add all those files to a MD and merge into one file. The goal is to do that with multiple DG Images based on the satellite type.

The issue I am getting is sometimes the pyramids are failing to build on the output files in the Clone folder. Even if they are succeeding, when I visualize the MD nothing is showing up except for the footprint of the merged files.

The MRFs in the Clone folder do not have pyramids after the OptimizeRaster tool is run; is this where I need to adjust the XML based on the @gsumerling comment above?

Thanks!
Chris

**Comment by Chamlika** [comment]
Chris, 
  I looked up the log file from you and for some reason GDAL is failing to read the rasters related to the file WV01/054872572010_01/054872572010_01_P001_PAN/15AUG17050640-P2AS-054872572010_01_P001.TIL with permission issues/errors from GDAL like (ERROR 1: TIFFFetchStripThing:IO error during reading). This is unusual and could be related to source GD rasters. One question, did you get the OptimizeRasters working properly on any other GD related data besides the ones found in path (WV01/054872572010_01/)? Need to know if this is an isolated case. Thanks.

**Comment by cjgabris** [comment]
@Chamlika For any of the DG images I run the tool on I get the same general errors. I have tried with a few WV01 and GE01 DG images. All of the processes move data to s3 and create the 100+ MRF files in the Clone dir.

**Comment by Chamlika** [comment]
@cjgabris OK. I'm not sure if this error from GDAL could be safely ignored at the moment. It looks like you've got all the data uploaded to S3 and the clone files created but possibly due to this error couldn't complete the pyramid creation process. I see that error in the original log file sent. This could be even due  to out of disk space (double check on that) or an access issue of some sort. I'll check if I could duplicate this with few GD samples here.

**Comment by cjgabris** [comment]
@Chamlika Thank you. If there is something I can send that would help to replicate, please let me know. I do not think disk space is the issue.

**Comment by Chamlika** [comment]
@cjgabris OK I could duplicate this. Will notify you once fixed and tested. Thanks.

**Comment by cjgabris** [comment]
@CodyBenkelman With adjustments to my XML and .py files, I've rerun the OptimizeRaster tool and do not get the errors referenced in my earlier posts. However, I get a new error when trying to build pyramids on the resulting raster datasets in my clone directory. Any suggestions on how to best visualize the results in the clone directory? I tried Overviews but didn't get better results.
![optimizeraster3](https://cloud.githubusercontent.com/assets/8806479/17447938/640a3770-5b1f-11e6-9ad2-0d6ce9880117.jpg)
