### ISSUE TITLE
10.5 Support??

### ISSUE THREAD

**Issue by Petwet2000** [Esri/OptimizeRasters#43]
Hi Is OptimizeRaster supported at 10.5? I ask because I am unsuccessful in using Optimizeraster with 10.5 to convert elevation tiff's to MRF with LERC compression.

Thanks,

**Comment by RandallRebello** [comment]
Hi, 
Can you please provide some more details in the problem you are facing.  Would it be possible to provide the log file for this issue. Are you facing problems with the UX? 
Thanks,
Randall

**Comment by Petwet2000** [comment]
Hi Randall,

The log file attached.

Cheers,

Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>

**Comment by RandallRebello** [comment]
Hi Christopher
I think you forgot to attach the log file.. 

Randall

**Comment by Petwet2000** [comment]
Hi Randall,

It was attached but I think your system filtered it. I attached it again but changed the extension to “.txt.” Let me know if it’s missing again.

Cheers,

Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>

**Comment by Chamlika** [comment]
@Petwet2000  It looks like your copy of OptimizeRasters is slightly outdated. Could you try with the latest setup available @ https://github.com/Esri/OptimizeRasters/raw/master/Setup/OptimizeRastersToolsSetup.exe and let us know. Thanks.

**Comment by Petwet2000** [comment]
Ok will do.

Thanks,

Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>

**Comment by Petwet2000** [comment]
Hi Chamlika,

Do you recommend I uninstall the older version first?

Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>

**Comment by Chamlika** [comment]
@Petwet2000   No need, the new setup should just overwrite the existing files. There's no windows registry entry modifications done by the setup, so it's completely safe.

**Comment by Petwet2000** [comment]
Ok thank you.

Christopher Patterson | Imagery Solutions Specialist
Esri Canada | 430-1600 Carling Ave | Ottawa ON K1Z 1G3
T 613-691-2068 | M 613-297-0897 | esri.ca<http://esri.ca/>
