### ISSUE TITLE
BlobService import fails

### ISSUE THREAD

**Issue by Lewis-Birkett** [Esri/OptimizeRasters#44]
When running the ProfileEditor to create an azure profile, it fails with the error "Azure" object has no attribute "_blob_service". 
![image](https://cloud.githubusercontent.com/assets/20474865/26671968/4b9b37bc-46af-11e7-84f6-9ecb533b6758.png)

Having a look, I belive the error is with this section in "OptimizeRasters.py":

In Class Azure (line 1710): "from azure.storage.blob import BlobService"

The latest version of the azure python sdk does not contain this module.

Changing the code to use "BlockBlobService" appears to fix this, can you confirm?

**Comment by Chamlika** [comment]
Lewis,
   Thanks for reporting. OptimizeRasters has been updated to work with the latest azure module.
Please update from GitHub.

Cheers,
Chamlika

**Comment by Lewis-Birkett** [comment]
I believe your latest update has brought this issue back.

**Comment by Chamlika** [comment]
Lewis,
     Thank you informing. You're right, the fix was left out during an upgrade. Please update from GitHub.

-Chamlika

Sent from my Windows Phone
________________________________
