### ISSUE TITLE
GUI Tool not working - Still works on console

### ISSUE THREAD

**Issue by nsteffens** [Esri/OptimizeRasters#45]
I'm trying to run the tool inside of ArcGIS 10.5. I want to create RasterProxyFiles from .tif files inside of an AWS S3 bucket and get the following error message:

> log-critical: Invalid input S3 bucket (--bucket-name--)/credentials
> log-critical: Unable to initialize S3-storage! Quitting..

The thing I don't understand is that if I run the tool on the console, using the same parameters (taken from the log-file of the GUI approach) everything works fine and a RasterProxyFile is created.

There is one Policy on the S3 bucket active which assigns the s3:GetObject action to our instance. Does it need more policies?

Thanks in advance!

**Comment by Chamlika** [comment]
@nsteffens  How was the bucket name entered on the UI, was it selected from the input bucket drop down list or typed in manually? If you can please share the log file generated when run from the UI. Thanks.

**Comment by nsteffens** [comment]
Thanks for your reply. I selected the bucket name from the drop-down menu as it loaded all of my buckets. Please see the content of the log file attached.

I also updated the version of boto3 using pip. As you probably see i anonymized my bucket name. The only 'special' character that is used is a minus (-).

Thanks in advance!

[OR_20170704T150123224000_20170704T150123.txt](https://github.com/Esri/OptimizeRasters/files/1128017/OR_20170704T150123224000_20170704T150123.txt)

**Comment by Chamlika** [comment]
@nsteffens I'm unable to duplicate the issue on my side. Could you give me the exact bucket name used?

**Comment by nsteffens** [comment]
The exact name of the bucket is 'ifgi-copernicus-image-processing'. I also did a short video demonstrating the issue: https://uni-muenster.sciebo.de/index.php/s/XBtnAnzSr7vHsSl

**Comment by Chamlika** [comment]
Nico,
     Thanks for the video demonstration. The ‘input path’ text requires only the folder name without the file name. Could you take out the file name from the input path text and see if it works. Thanks.

**Comment by nsteffens** [comment]
I just removed the file name and just inserted the folder name where multiple .tif files are stored. I still get the same error message. As I already stated, if I run it on the command line it works fine.

**Comment by Chamlika** [comment]
@nsteffens  Can you run the OptimizeRasters session in the foreground within ArcMap (Disable background processing) and send me the text that show up in the progress window? Please don't modify anything in text before sending so that I know exactly what was sent across. Thanks.
