### ISSUE TITLE
Use custom aws_endpoint_url

### ISSUE THREAD

**Issue by zhouning** [Esri/OptimizeRasters#48]
When use custom aws_endpoint_url:   http://oss-cn-hongkong.aliyuncs.com (this is AWS S3 Compatible),
I found that the code   OptimizeRastersUI.getAvailableBuckets() or ProfileEditorUI.validateCredentials() can not get _availableBuckets,may be because the code:
con = session.resource('s3')
lost parameter "endpoint_url=url"?

**Comment by Chamlika** [comment]
@zhouning Do you think you still have this issue with the version currently on GitHub?
