### ISSUE TITLE
HTTP response code: 403 - Failed writing header

### ISSUE THREAD

**Issue by asalool** [Esri/OptimizeRasters#52]
I have the raster files in S3 and I'm using an IAM role to access it. When I run the tool on raster proxy mode I'm getting 'HTTP response code: 403 - Failed writing header' error directly after trying to apply compression with the vsicurl command. I can confirm that there is no issues at all in accessing the files on S3 as all of the non imagery files can be accessed and downloaded to the local output folder. Below are the logs for more information 

Log-path set to (c:\Users/xxx/desktop\image_mgmt_workflows\optimizerasters\logs\logs)
log-msg:version=v2.0.1j/20180412
log-msg:-clouddownload="true" -clouddownloadtype="amazon" -config="C:/Users/xxx/Desktop/Image_Mgmt_Workflows/OptimizeRasters/OptimizeRasters.xml" -input="sample" -inputbucket="igbuild-gis" -inputprofile="iamrole:gis-dev01-role" -mode="rasterproxy" -output="C:/Users/xxx/Desktop/RP2" -s3input="true" -tempinput="C:/Users/xxx/Desktop/temp"
log-msg:ExcludeFilter=[u'tmp', u'ovr', u'rrd', u'idx', u'lrc', u'mrf_cache', u'pjp', u'ppng', u'pft', u'pzp']
log-msg:BuildPyramids=true
log-msg:Compression=lerc
log-msg:Out_S3_ID=Out_S3_ID
log-msg:KeepExtension=True
log-msg:BlockSize=512
log-msg:Out_S3_DeleteAfterUpload=True
log-msg:Out_S3_Bucket=Out_BucketName
log-msg:LogPath=C:\Users\xxx\Desktop\Image_Mgmt_Workflows\OptimizeRasters\logs
log-msg:PyramidFactor=2 4 8 16 32 64
log-msg:Out_S3_Upload=F
log-msg:Threads=2
log-msg:Mode=rasterproxy
log-msg:RasterFormatFilter=[u'tif', u'TIF', u'mrf']
log-msg:Out_S3_Secret=Out_S3_secret_key
log-msg:PyramidCompression=JPEG
log-msg:Quality=85
log-msg:IncludeSubdirectories=True
log-msg:Out_S3_ParentFolder=Out_S3Partent_folder
log-msg:[Resume] Creating job (C:\Users\xxx\Desktop\Image_Mgmt_Workflows\OptimizeRasters\OR_20180419T052023932000.orjob)
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7045000.ERS
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7045000.mrf.aux.xml
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7045000.pjg
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7045000.prj
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7045000.tab
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7046000.ERS
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7046000.mrf.aux.xml
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7046000.pjg
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7046000.prj
log-msg:[S3-Pull] C:/Users/xxx/Desktop/RP2/716000-7046000.tab
log-msg:
Processing caching operations...
log-msg:Applying compression (/vsicurl/http://igbuild-gis.s3.amazonaws.com/sample/716000-7045000.tif)
log-msg:Applying compression (/vsicurl/http://igbuild-gis.s3.amazonaws.com/sample/716000-7045000.mrf)
log-msg:warnings/errors:
log-msg:ERROR 11: HTTP response code: 403 - Failed writing header
log-msg:Status: (FAILED).
log-msg:Applying compression (/vsicurl/http://igbuild-gis.s3.amazonaws.com/sample/716000-7046000.mrf)
log-msg:warnings/errors:
log-msg:ERROR 11: HTTP response code: 403 - Failed writing header
log-msg:Status: (FAILED).
log-msg:Applying compression (/vsicurl/http://igbuild-gis.s3.amazonaws.com/sample/716000-7046000.tif)
log-msg:warnings/errors:
log-msg:ERROR 11: HTTP response code: 403 - Failed writing header
log-msg:Status: (FAILED).
log-msg:warnings/errors:
log-msg:ERROR 11: HTTP response code: 403 - Failed writing header
log-msg:Status: (FAILED).
log-msg:Done..

log-status:[Failed!]
Time taken> 5.614s

Done..

**Comment by Chamlika** [comment]
@asalool  Could you use -usetoken=true at the cmd-line and give it another try?  -usetoken must be used with EC2 instances with IAM role based security.

**Comment by asalool** [comment]
Thanks @Chamlika , it's working fine for me now. I wish this was highlighted in the documentation

**Comment by asalool** [comment]
@Chamlika I can't view the created raster proxy files in ArcMap, is there any compatibility issues with ArcGIS 10.6? I can add them without any errors and I can access raster information

**Comment by abhiataero** [comment]
@asalool  can you check if you have the permission to access the data from the s3 bucket. easy way to do that is to open the URL is a browser, it wil tell you if there is an issue for access

**Comment by asalool** [comment]
@Chamlika I can confirm that I have the permission to access the data, actually I can't create the raster proxy files if I don't have the access. I can successfully create the files using the below command, I appreciate your assistance 

C:\Python27\ArcGIS10.6\python.exe C:\Users\user\Desktop\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py -inputprofile=iamrole:gis-dev01-role -clouddownload=true -clouddownloadtype=amazon -usetoken=true -inputbucket=ig-gis -input=sample/ -output=C:\Users\user\Desktop\RP -s3input=true –mode=rasterproxy

**Comment by lucianpls** [comment]
There are two ways to consume files from S3, one is using IAM and /vsis3, while the other one uses unsigned HTTP GetObject access, via /vsicurl.
You might have access via IAM and the token but if the proxies are set up via /vsicurl you would need unsigned GetObject access, which is controlled by the source bucket policy.
Look inside the proxies, do they have links that start with /vsis3 or with /vsicurl?

**Comment by Chamlika** [comment]
@asalool  Could you attach one of your proxy files? Also see if the below command makes any difference in the output proxy files, 
C:\Python27\ArcGIS10.6\python.exe C:\Users\user\Desktop\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py -inputprofile=iamrole:gis-dev01-role -clouddownload=true -clouddownloadtype=amazon -usetoken=true -inputbucket=ig-gis -input=sample/ -output=C:\Users\user\Desktop\RP -s3input=true **–config=C:\Users\user\Desktop\Image_Mgmt_Workflows\OptimizeRasters\Templates\CreateRasterProxy.xml**

**Comment by Chamlika** [comment]
@asalool  Can you check if the folder path C:/Users/ahmed.elsalloul1/Desktop/RP/ exists on the disk?  The raster(s) don't show up if the paths <DataFile> and <IndexFile> in the proxy file don't exist.  Also see if the raster shows up if both paths are set to **C:/temp/**ahmed.elsalloul1/Desktop/RP.  This is just to test if it's a folder permission issue that we're dealing with here. Thanks!

**Comment by asalool** [comment]
@Chamlika Yes the folder exists, and I can see that cache files are being created. I've updated the paths as per your request and I'm still having the same issue

**Comment by abhiataero** [comment]
@asalool , it seems you are using vsis3 to access the data for this the system environment variables needs to be setup. 
set be below as system environment variables and restart arcmap 
AWS_SECRET_ACCESS_KEY=<yoursecret_key>
AWS_ACCESS_KEY_ID=<youraccess_key>
GDAL_HTTP_UNSAFESSL=TRUE
 
also clean the cache, if still face the issue i can connect with you to identify the issue

**Comment by asalool** [comment]
@abhiataero the proxy files are accessing raster files through an IAM role, and setting up the AWS_PROFILE variable solve the issue. Thank you all for your assistance, I believe this should be highlighted in the user guide.
