### ISSUE TITLE
Resume jobs

### ISSUE THREAD

**Issue by KazzaS** [Esri/OptimizeRasters#53]
Hi,

Over the weekend I was running a Imagery_to_MRF_JPEG OptimizeRaster script using many tif files in many folders on the S3 over weekend and it stalled because of an 'gdaladdo.exe has stopped working' error which eventually crashed the computer, therefore the .orjob file did not contain the yes's and no's to run the Resume tool.  All the tifs were downloaded to my computer, hundreds of GBs.  How can I add the yes's and no's in the .orjob file so that only the tifs get compressed and uploaded as mrf to S3 without being deleted, see below  (ps:I already set <Out_S3_DeleteAfterUpload> to false)

SOURCE	COPIED	PROCESSED	UPLOADED
#####/#####/##_Tiff_RGB_tiles_##/			
#####/#####/##_Tiff_RGB_tiles_##/Thumbs.db			
#####/#####/##_Tiff_RGB_tiles_##/##/##/##.tif	yes	no

Also c:\Python27\ArcGIS10.4\python.exe c:\Image_Mgmt_Workflows\OptimizeRasters -input=OR_20151211T024329630000.orjob command line code gives me a python ___main____ error, so I have to run it via the OptimizeRaster tool which is slower.

Also, is there a way to only do the processing in batches, instead of it doing a copy, [S3-Pull] of all tifs to the local tempinput folder?

Many thanks for your help,
K

**Comment by Chamlika** [comment]
@KazzaS I believe there's a typo in your usage, the usage should've been  c:\Python27\ArcGIS10.4\python.exe c:\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py -input=OR_20151211T024329630000.orjob

Also, If the tiff files have already been downloaded, I'd suggest to set the -input to the local disk path where the rasters are located (skipping the s3 pull operation by removing the download=true inputbucket=xx -inputprofile=xx  tempinput=xx flags from your usage) and to upload rasters/files to S3 once done with processing. 

Also please make sure you're on the latest version on GitHub. Code was added few months ago to update the orjob status fields every 20 seconds to create snapshot of the progress for longer running processes.

**Comment by KazzaS** [comment]
Hi Chamlika,  Thanks for your quick reply.  I have put my feedback in highlighted italics below.
Kind regards,
K.
Ps: this is the first time I post on the GitHub OptimizeRaster Issue board, will this email reply also be posted?

**Comment by Chamlika** [comment]
@KazzaS I believe the problem could be due to lack of disk space. This could be the reason why the gdaladdo.exe was stuck in the background or it could be data specific if it was known to happen only with few rasters. Yes, setting the -tempinput can run you into the risk of using up disk space before processing. If you omit -tempinput however,  the rasters will be processed directly without the need to download them first locally. See if that mode suits your workflow.
