### ISSUE TITLE
Raster proxies created using the cog conversion have extension as tiff.congtiff

### ISSUE THREAD

**Issue by vijaygit02** [Esri/OptimizeRasters#54]
This issue happens when the raster proxy path is given as one of the option while converting the files. Haven't really tried with just "CreateRasterProxies" Template.
The 2 additional issues related to the the above are:
 1.The source path in the raster proxy also has a file with tif.cogtiff extention.
 2.The raster proxy directory is getting copied to the S3 bucket.

**Comment by Chamlika** [comment]
Fixed. Please update to the latest GitHub version.
