### ISSUE TITLE
Create Raster Proxy Failing

### ISSUE THREAD

**Issue by Petwet2000** [Esri/OptimizeRasters#57]
Hi I copied some tiff's to S3 bucket then tried to create raster proxies to a local machine and the process fails with following message:
"Processing caching operations...
log-msg:Applying compression (/vsicurl/http://cpimagery.s3.amazonaws.com/amberg/090160.tif)
log-msg:warnings/errors:
log-msg:ERROR 11: HTTP response code: 307 - Failed writing header
log-msg:Status: (FAILED).
log-msg:Done..

log-status:[Failed!]
Completed script OptimizeRasters...
Succeeded at Fri Jun  1 15:14:34 2018 (Elapsed Time: 5.26 seconds)

The file was uploaded no problem using the Copy file template in OptimizeRaster.

**Comment by abhiataero** [comment]
@Petwet2000 The issue here also seems with the permission or set the access keys to read the data

**Comment by Petwet2000** [comment]
Hi,

This is related to case#58. So we can close this one. Thanks for responding.

Cheers,
