### ISSUE TITLE
Working with Private Data in S3 & EC2 using OptimizeRaster

### ISSUE THREAD

**Issue by Petwet2000** [Esri/OptimizeRasters#58]
Hi,
I am working with some satellite and elevation data in a private bucket on S3. I am using IAM role to access the data. When i try to build raster proxies from EC2 using OptimizeRaster, the process keeps failing (403 error). How do I pass the "-usetoken=true" command using OptimizeRaster(OR) UI? Also I found a previous post (52) that suggested setting system variables which I did build can't get OR UI to work.

Note: If I use the commandline the process works but the client I am working with prefers the UI.

thanks,

**Comment by Chamlika** [comment]
@Petwet2000 -useToken is not yet supported through the UI but expected to get it in the next update.

**Comment by Petwet2000** [comment]
Thanks for responding. Any ideas when that will be? Also will OR UI work with the system variables required when using IAM role?

Thanks

**Comment by Chamlika** [comment]
@Petwet2000 By next week. System environment variables should've always worked within the UI. Could you tell me what environment variables that you need to set for IAM roles? Presently there isn't any need in OptimizeRasters to set any environment variables by users unless you need to set any for GDAL.

**Comment by Petwet2000** [comment]
Hi,
I had to set the following system variables for the command line to work properly.
AWS_SECRET_ACCESS_KEY=<yoursecret_key>
AWS_ACCESS_KEY_ID=<youraccess_key>
GDAL_HTTP_UNSAFESSL=TRUE

What I found is that running the create raster proxy script without setting the variables produced raster proxies that does not display in ArcMap. I can see them in the folder but no image.

**Comment by Chamlika** [comment]
@Petwet2000 GitHub has been updated.
UseToken key is now supported within the OptimizeRaster GP Tool UI/Advanced/Configuration values table. To enable access to IAM role based restricted data, set the value of UseToken key to True by following the steps shown below,

1. -Use the 'Profile Editor' UI within ArcMap/Pro.
   -Enter a new profile name of your choice. 
   -Check on the 'IAM Role Profile' 
   -Press on the 'OK' button to save.

2. -Click on the OptimizeRasters UI
   -Select the input profile created in step 1. Note, the profile name is prefixed with 'iamrole:' 
   -Fill in the rest of the text box entries as required. 
   -Expand the 'Advanced' section.
   -Click on the 'Edit Configuration Value' check box. 
   -Scroll down the key/value table to find the key 'UseToken' and set its value to True.
   -Press on the 'OK' button to proceed with processing.

**Comment by Petwet2000** [comment]
Thanks a lot for this Chamlika. I will test it and get back to you. Question:
Since we are using IAM roles with the GUI, why do I need to set environment variables for the process to work?

**Comment by Chamlika** [comment]
@Petwet2000 You do not have to set any environment variables manually. Necessary settings will be taken of internally.

**Comment by Petwet2000** [comment]
wonderful! I will try this and let you know.

**Comment by Petwet2000** [comment]
Hi Chamlika,
Some info for you. 
1. Bucket setup with IAM role access. 
2. I tried the new workflow you sent with the OR GUI. 
3. Raster proxies were created but showed blank in ArcMap.
4. Closed ArcMap and added the following system variables:
   a.	AWS_SECRET_ACCESS_KEY=<yoursecret_key>
        AWS_ACCESS_KEY_ID=<youraccess_key>
        GDAL_HTTP_UNSAFESSL=TRUE

5. Open ArcMap and reran the test of building proxies.
6. Proxies created successfully and the images displayed in ArcMap as expected.

It appears the process doesn't work with the system variables. Did you get it to work with the system variables?

**Comment by Petwet2000** [comment]
Sorry ..that last comment should have been:

"It appears the process doesn't work **without** the system variables. Did you get it to work with the system variables?

**Comment by Chamlika** [comment]
@Petwet2000 I've a feeling that it's the ArcMap that needs these system environment variables and not the raster proxy file creation process through OptimizeRasters. To confirm, do you see any difference in the output raster proxy files with and without the environment variables set?

**Comment by abhiataero** [comment]
@Petwet2000 What is the version of ArcGIS, if you have the IAM polices set correctly you will not need the environmental to be set

**Comment by Petwet2000** [comment]
Arcmap version is 10.5 and 10.6. From both versions I have experienced this problem.

**Comment by abhiataero** [comment]
@Petwet2000 is there any way we can do a screen share

**Comment by Petwet2000** [comment]
Yes we can. When are you available? I can send you a webex invite.

**Comment by abhiataero** [comment]
i am available now, can i have your email

**Comment by Petwet2000** [comment]
Ok let's connect. email on its way.

**Comment by Petwet2000** [comment]
issue resolved. When using IAM role to access data in S3 the above environment variables are not required. If data is being accessed via public access (vsicurl..) the GDAL_HTTP_UNSAFESSL=TRUE variable is required.
