### ISSUE TITLE
Unable to initialize (Copy) module!

### ISSUE THREAD

**Issue by michaelblair** [Esri/OptimizeRasters#62]
![image](https://user-images.githubusercontent.com/22747813/44873781-2d837900-ac67-11e8-9966-cc0774586aa9.png)

**Comment by Chamlika** [comment]
@michaelblair from the screenshot it looks like the input folder contains the tiff file name as well. Could you enter just the input folder name and check to see if gets through.  Thanks!

**Comment by michaelblair** [comment]
@Chamlika Thank you for that input.  We're running a test now and all appears to be working.

**Comment by michaelblair** [comment]
![image](https://user-images.githubusercontent.com/22747813/44924808-7c3e1b00-ad1a-11e8-8e57-4b0566c3b8c8.png)

@Chamlika When trying to create raster proxy using tif that's stored on a S3 bucket.  The workflow we're attempting using: 1. Copy TIF to S3 2. Create raster proxy 3. Publish proxy as image service.  Is this workflow correct or should we modify?  We have a large raster that we want to store on S3 and use it as a dataset for raster analytics as well as image service for web app.

**Comment by abhiataero** [comment]
@michaelblair are just copying the Tif to S3 or converting and copying to S3

**Comment by michaelblair** [comment]
We've tried both copying and converting and copying and both methods get the 404 response.

**Comment by abhiataero** [comment]
@michaelblair it seems the issue is with the permission to the data on s3, can you try to open the s3 URL in the browser and check if you permission

**Comment by michaelblair** [comment]
@abhiataero Thanks for the feedback.  I made the S3 folder public and appears that the conversion was successful.  Hopefully last question/issue, when we try and publish an Image Service from resultant RasterProxy we continue to get an error with image service.  Is there a workflow that should be used for that that we're missing?

**Comment by abhiataero** [comment]
@michaelblair what is the error you are getting 
- is the server same machine that you are building the raster proxy

- Are you publishing the mosaic by refrence or by value

**Comment by michaelblair** [comment]
@abhiataero The workflow that I'm following is:
1. From local machine run Imagery_To_MRF_LERC for .tif - success
2. Copy resulting MRF to S3 - success
3. Create raster proxy utilizing MRF in S3 and save proxy to local machine - success
4. Publish raster proxy as Image service in 10.6 - crash of ArcCatalog

**Comment by abhiataero** [comment]
@michaelblair check with the updated version of Optimize raster the workflow about works fine
