### ISSUE TITLE
Optimize Raster is not able to create proxies for more than 1000 images

### ISSUE THREAD

**Issue by abhiataero** [Esri/OptimizeRasters#63]
Optimize Raster is not able to create proxies in the input folder has more than 1000 sub folders or images

**Comment by Chamlika** [comment]
@abhiataero  The issue was related to input path that has >1000 (subfolders) and not when >1000 rasters at root of the input path. The issue has been corrected to work with larger number of subfolders as well.

**Comment by Chamlika** [comment]
Fix to be made available in the next GitHub push.
