### ISSUE TITLE
some of the GDAL user parameters are not taken in account

### ISSUE THREAD

**Issue by abhiataero** [Esri/OptimizeRasters#66]
When using MRF_LERC template, i have defined the GDAL user parameter -co OPTIONS="DEFLATE=ON"

the output generated ignored it

**Comment by Chamlika** [comment]
Need more info, what was the template used, perhaps the GDAL ignored the user options based on the conversion requested.

**Comment by lucianpls** [comment]
The deflate option is never ignored in MRF
