### ISSUE TITLE
CreateRasterProxy Template blocks entry of Output Temporary Folder

### ISSUE THREAD

**Issue by slibby** [Esri/OptimizeRasters#67]
If using the .pyt `OptimizeRasters` with the CreateRasterProxy template from local to S3, the tool fails and errors that the Output Temp Folder is missing, but the UI blocks that folder from being set. 

![image](https://user-images.githubusercontent.com/1691225/46681990-ad2b2e80-cba9-11e8-8520-3b68aac819f8.png)

![image](https://user-images.githubusercontent.com/1691225/46682022-bfa56800-cba9-11e8-883b-c2e1671591c5.png)

Should this template allow this parameter to be set instead?

**Comment by slibby** [comment]
I understand this may not be the right workflow - so if that is irrelevant disregard and close this issue. I was able to get things working using `Imagery_to_MRF_LERC`->`CopyFilesOnly`->`CreateRasterProxy`

**Comment by Chamlika** [comment]
@slibby CreateRasterProxy template is to be used when you've source rasters on a cloud store and you'd like to create proxy files (locally) so that the original rasters can be referenced.  Is there any reason why you'd want to push the locally produced raster proxy files to cloud?

**Comment by slibby** [comment]
@Chamlika thanks - This was my misunderstanding early in my OptimizeRasters days :)
