### ISSUE TITLE
Add support for reading from VRTs

### ISSUE THREAD

**Issue by jameswelliott** [Esri/OptimizeRasters#68]
Reading from VRTs would be very useful, or at the minimum, allow the selection of what bands of the source raster we want to have in the optimized output please.

**Comment by PBecker92373** [comment]
To define bands etc check out GDAL_Translate_UserParameters in the documentation. You can defined -b1 -b2 -b3 etc

**Comment by abhiataero** [comment]
@jameswelliott if you have VRT as input in that case in the template set VRT as a Rasterformat, and the file extension that it refers needs to be set in the exclude filter 
<RasterFormatFilter>vrt,VRT</RasterFormatFilter>
    
    <ExcludeFilter>tif,tiff,TIF,TIFF,img,jp2,JP2,IMG,JPG,jpg,sid,SID,tmp,rrd,idx,lrc,mrf_cache,pjp,ppng,pft,pzp,ovr,aux.xml,aux,tfw,TFW,pjg</ExcludeFilter>

**Comment by jameswelliott** [comment]
Thanks!

I’ll give that a shot.


  *   James
