### ISSUE TITLE
OptimizeRastersLambdaFX.zip missing from repo

### ISSUE THREAD

**Issue by stormchasing** [Esri/OptimizeRasters#69]
OptimizeRaster_Lambda_UserDoc has a link to the Lambda function on page 1 (https://github.com/Esri/OptimizeRasters/tree/master/Setup/Lambda) , but the zip file is not at the link location or anywhere else in the repo.

**Comment by Chamlika** [comment]
@stormchasing The lambda setup is now on GitHub. Thanks!
