### ISSUE TITLE
Profile Editor no longer displays IAM Role option - Update Documentation

### ISSUE THREAD

**Issue by slibby** [Esri/OptimizeRasters#70]
IAM Roles are no longer set up in the profile editor, as I understand it, but are assumed during the run of OptimizeRasters. This change seemed to happen in https://github.com/Esri/OptimizeRasters/commit/0c12b265add6473774db35ac377c8e892d39f6ca but was not noted in the release notes. 

Can we update the documentation to better reflect how to use IAM roles? I was very confused for a few hours as the entire approach changed. Also we can update the tool help for the toolbox.

**Comment by Chamlika** [comment]
@slibby The OptimizeRasters self detects the run environment (IAM Role based/credential key pair access based/OS type e.t.c.) and the OptimizeRasters takes the necessary steps to grant access or to form the proper URL syntax to allow access to the required AWS resources.
Will have few extra notes on this subject in the next available doc version.

**Comment by slibby** [comment]
Thanks @Chamlika  I need to test with the current version - I thought it was "mostly" working last time I tried. I will re-post here with an update on issues.
