### ISSUE TITLE
IAM Roles now require ListBuckets?

### ISSUE THREAD

**Issue by slibby** [Esri/OptimizeRasters#71]
It appears to me that using IAM roles now requires that role to have ListBuckets available as an IAM privilege. This was not the case prior to the most recent release and reflects a security issue for some organizations as ListBuckets is a broad privilege. I believe this could be addressed in the .pyt quite simply somewhere around lines https://github.com/Esri/OptimizeRasters/blob/master/OptimizeRasters.pyt#L748 and https://github.com/Esri/OptimizeRasters/blob/master/OptimizeRasters.pyt#L800. Currently if ListBuckets is not available, the UI "blanks out" the Bucket name, not letting you put one in manually (see gif below)
![2018-10-23_14-44-12](https://user-images.githubusercontent.com/1691225/47389501-25c5db00-d6d2-11e8-9f36-d58f42b8a047.gif)

This also "blanks out" for the output bucket. Ideally it would let you manually enter a bucket name if nothing is returned from ListBuckets()
cc @PBecker92373 @ewindahl

**Comment by slibby** [comment]
a hacky fix to this can be found here: https://gist.github.com/slibby/ef2e2b542b5e29e926f1ada33ae19f00

By removing a bunch of tool validation, this lets you enter bucket names manually.

**Comment by gbrunner** [comment]
@slibby I also run into this ListBuckets issue when trying to run **Profile Editor**. The error I get says: *An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key ID you provided does not exist in our records*.

@PBecker92373 @ewindahl I could see this being an issue for users who don't have access to all the buckets in an account. Does there need to be a call to ListBuckets?

**Comment by slibby** [comment]
@abhiataero @Chamlika any feedback on this?

**Comment by Chamlika** [comment]
@slibby Could you resort to using the OptimizeRasters via the console/DOS window until the UI fix is made available?
