### ISSUE TITLE
Not getting rasterproxyfiles in synchronously called lambda

### ISSUE THREAD

**Issue by stormchasing** [Esri/OptimizeRasters#73]
I'm passing in a rasterproxypath, but the rasterproxyfiles in respJSON from the lambda function call is always empty. Is there something I need to be doing to get the rasterproxy information back from the lambda call?

**Comment by stormchasing** [comment]
Okay, I was curious since I saw an empty "RasterProxyFiles" object being created in lambda_function.py. I was going to try and toss that json into an SNS topic. I think I'll go ahead and see if I can do what needs to be done to get that object to populate with the rasterproxy files. Trying to accomplish a serverless workflow using lambdas since we have two times per day when a few thousand tiffs are triggering the OptimizeRasters lambda and I'd like to get the rasterproxies available as quickly as possible.

**Comment by abhiataero** [comment]
@stormchasing i am closing this issue. FYI we have a container for optimize raster in case you need that.
