### ISSUE TITLE
Incorrect path for GDAL library files given in lambda docs

### ISSUE THREAD

**Issue by stormchasing** [Esri/OptimizeRasters#74]
Instructions call for the LD_LIBRARY_PATH environment variable to be set to /var/task/GDAL/lib, but these files are in /GDAL/bin in the lambda zip so the variable should be /var/task/GDAL/bin.

**Comment by Chamlika** [comment]
@stormchasing Thank you for reporting. Will have the doc updated.

**Comment by ewindahl** [comment]
Lambda doc is updated. Thanks, @stormchasing.
