### ISSUE TITLE
IAM Roles not working on Command Line

### ISSUE THREAD

**Issue by slibby** [Esri/OptimizeRasters#76]
With the latest updates, it appears to me that the profile is not being recognized properly when using command line OptimizeRasters + IAM Roles. The UI uses `Using_EC2 Instance_with_IAM_Role` as the option for the profile. If I enter this in the command line, I need to wrap it in double-quotes like `-inputprofile="Using_EC2 Instance_with_IAM_Role"` as it includes a space (should it?) - and it fails regardless. Any ideas?

![image](https://user-images.githubusercontent.com/1691225/47731406-aa13e300-dc29-11e8-8205-6f1003c66120.png)

On the **Right** is a job that "worked" from the UI - though it creates raster proxy files that show up as black boxes in Pro. on the left is command line using the exact same parameters as the .orjob and failing.

**Comment by abhiataero** [comment]
@slibby can you upgrade to the recent version of optimize Raster and check, i have tested it out and works 

Does the EC2 instance you are running have IAM role attached 

c:\Python27\ArcGIS10.6\python.exe c:\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py  -config=c:\Image_mgmt_Workflows\OptimizeRasters\Templates\CreateRasterProxy.xml -clouddownload=true -inputbucket=eeeeee -clouddownloadtype=amazon  -input=eeeeee/ -output=c:/temp/iamest -usetoken=false -inputprofile="Using_EC2_Instance_with_IAM_Role"

**Comment by slibby** [comment]
@abhiataero Yes, we have an IAM role attached - I am testing with the latest version as well (from 3 days ago). So is what you're saying that the argument should be `"Using_EC2_Instance_with_IAM_Role"` with the underscore between EC2 and Instance?   I am trying to test further but having issues now with GDAL loading dlls.

**Comment by slibby** [comment]
Ah! Setting usetoken=true made it use vsis3 - this works now! Is there something that we can update in the doc to reflect that?

**Comment by slibby** [comment]
Interestingly, it seems to work using Desktop 10.6.1 Python:
```
c:\Image_Mgmt_Workflows\OptimizeRasters\GDAL\bin>c:\Python27\ArcGIS10.6\python.exe 
c:\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py 
-config=c:\Image_mgmt_Workflows\OptimizeRasters\Templates\CreateRasterProxy.xml 
-clouddownload=true -inputbucket=abt-arcgis-prod-image -clouddownloadtype=amazon
-input=mrf_1220/ -output=c:/imagery/proxyfiles -usetoken=true 
-inputprofile="Using_EC2_Instance_with_IAM_Role"
```

but not work in Pro Python:

![image](https://user-images.githubusercontent.com/1691225/47864246-c2693680-ddbe-11e8-8259-217329b2e0fb.png)

**Comment by slibby** [comment]
@Chamlika the "secured bucket" checkbox seems to only be available for the input bucket, is there an option for the output bucket that should be there?

**Comment by Chamlika** [comment]
@slibby There was an issue with not updating the raster proxy files URL prefix properly when the input was from the local disk and context was an IAM Role based machine. This has been fixed on the last GitHub push. Thank you for catching it.
The 'secured bucket' checkbox is a common flag that acts on both the input and the output bucket.

**Comment by slibby** [comment]
Thanks @chamlika, in the case of a master to mrf/ local to S3 operation, how would you check the ‘Secured Bucket’ checkbox as it only appears in the input section when Input=S3 is checked.
________________________________
