### ISSUE TITLE
Raster Proxy process creates blank images

### ISSUE THREAD

**Issue by shingike** [Esri/OptimizeRasters#77]
We are processing large amount of UAV data from various format such as jp2, tif and jpeg into mrf/jpeg compression and uploading them to our Amazon S3 bucket. Our plan is to create raster proxy and create mosaic dataset using MDC.py and serve them through our ArcGIS Image Server.  We were successfully uploaded optimized mrf files over to S3; however, it is failing to create readable Raster Proxy files.

When it outputs raster proxy files with .mrf extensions, ArcGISPro/ArcCatelog recognizes them as rasters; however,  ArcGIS Pro displays black image extent with 0 values in RGB. Sizes of each raster proxy is only 1 and 2KB.

I have downloaded S3 MRF images to local and they are not corrupted. Followings are the console output with parameters. If you could let us know if there is any issue with the setup, I appreciate your input very much.

C:\Image_Mgmt_Workflows\OptimizeRasters>"C:\Python27\ArcGIS10.6\python.exe" "C:\Image_Mgmt_Workflows\OptimizeRasters\OptimizeRasters.py" -mode="rasterproxy" -s3input="s3bucketname/imagery_output" -input="imagery_output" -output="E:\ProjectImagery\raster_proxy" -tempoutput=K:\ProjectImagery\workspace -s3output=true -clouddownload=true -cache="E:\ProjectImagery\cache" -config="C:\Image_Mgmt_Workflows\OptimizeRasters\Templates\CreateRasterProxy.xml"

OptimizeRasters.py v2.0.2/20180705
Convert raster formats to a valid output format through GDAL_Translate.

Please Note:
OptimizeRasters.py is entirely case-sensitive, extensions/paths in the config file are case-sensitive and the program will fail if the correct path/case is not entered at the cmd-line or in the config file.

Log-path set to (C:\Image_Mgmt_Workflows\OptimizeRasters\logs)
log-msg:version=v2.0.2/20180705
log-msg:-cache="E:/ProjectImagery/cache" -clouddownload="true" -config="C:/Image_Mgmt_Workflows/OptimizeRasters/Templates/CreateRasterProxy.xml" -input="imagery_output" -mode="rasterproxy" -output="E:/ProjectImagery/raster_proxy" -s3input="s3bucketname/imagery_output" -s3output="true" -tempoutput="K:/ProjectImagery/workspace"
log-msg:ExcludeFilter=[u'tmp', u'rrd', u'idx', u'lrc', u'mrf_cache', u'pjp', u'ppng', u'pft', u'pzp', u'ovr', u'aux.xml', u'aux', u'tfw', u'TFW', u'pjg']
log-msg:Scale=3
log-msg:Compression=jpeg
log-msg:KeepExtension=True
log-msg:Out_Cloud_Type=Amazon
log-msg:In_S3_Bucket=s3bucketname
log-msg:Threads=4
log-msg:Out_S3_ACL=bucket-owner-full-control
log-msg:Out_S3_Secret=*************************************
log-msg:In_S3_Secret=*************************************
log-msg:RasterFormatFilter=[u'tif', u'tiff', u'TIF', u'TIFF', u'JP2', u'jp2', u'ntf', u'NTF', u'img', u'jpg']
log-msg:In_S3_ParentFolder=s3bucketname/imagery_output
log-msg:BlockSize=512
log-msg:In_S3_ID=*************************************
log-msg:Mode=rasterproxy
log-msg:Out_S3_Bucket=s3bucketname
log-msg:IncludeSubdirectories=true
log-msg:Out_S3_ParentFolder=s3bucketname/imagery_output
log-msg:BuildPyramids=true
log-msg:In_Cloud_Type=Amazon
log-msg:Out_S3_ID=*************************************
log-msg:PyramidCompression=jpeg
log-msg:CloudUpload=false
log-msg:PyramidSampling=average
log-msg:Quality=85
log-msg:[Resume] Creating job (C:\Image_Mgmt_Workflows\OptimizeRasters\OR_20181031T122422854000.orjob)
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/0004737.04-Lindahl Wind Mosiac.170620.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/0004737.04-Lindahl Wind Mosiac.170620.sdw
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Albany Drone Aerial 2017-02-17.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Annandale Drone Aerial 2017-02-10.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Atwater Drone Aerial 2017-02-23a.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Chisago Drone Aerial 2017-02-16.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Dodge Center Drone Aerial 2017-02-13.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Eastwood North Drone Aerial 2017-02-21.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Eastwood Solar Drone Aerial 2017-02-21.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Hastings Drone Aerial 2017-02-15.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Lake Emily Drone Aerial P3P 2017-02-06.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Lake Pulaski Drone Aerial 2017-02-22.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Lawrence Creek Drone Aerial 2017-02-16.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Montrose Drone Aerial 2017-02-23.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora Pine Island Drone Aerial 2017-02-13.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora West Faribault Drone Aerial P3P 2017-02-06.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Aurora West Waconia Drone Aerial 2017-02-23.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Paynesville MN Stearns Co.mrf
log-msg:[S3-Pull] E:/ProjectImagery/raster_proxy/Waseca Solar Waseca Co.mrf
log-msg:
Processing caching operations...
log-warning:No input rasters to process..
log-msg:[MV] C:\Image_Mgmt_Workflows\OptimizeRasters\logs\OR_20181031T122422854000.orjob
log-msg:Done..

log-status:[OK]
Time taken> 5.281s

**Comment by abhiataero** [comment]
@shingike 
In the raster proxy C:/Image_Mgmt_Workflows/OptimizeRasters/Templates/CreateRasterProxy.xml"

the RasterFormatFilter is missing mrf it should be 
<RasterFormatFilter>tif,tiff,TIF,TIFF,JP2,jp2,ntf,NTF,img,jpg,mrf,MRF</RasterFormatFilter>

**Comment by shingike** [comment]
Hi abhiataero,
Thanks for your comment.  As you have mentioned, the missing mrf on the RasterFormatFilter was one of issues I had.  I got it to work after fixing followings:

1. Add mrf, MRF to RasterFormatFilter.
2. Add idx,pjg,aux.xml to ExcludeFilter (to avoid unnecessary copy)
3. Add -usetoken="true" to use vsis3 for accessing secured bucket (mentioned in the Appendix B on the user document) 
4. Replace space with underscore to avoid GDAL Translate error 

Best,
Shingo

**Comment by shingike** [comment]
Hi abhiataero,
I am reopening this issue due to the re-occurrence of the exact same issue in my aws production machine. I have copied the working raster proxy files into a directory in aws production machine which has ArcGIS Server, Pro (2.1.2), Optimize Raster (2.0.2), and MDCS ().  The raster proxy and cache directories are under D:\drone_data directory and shared as data store in AGS.  When I copied the working raster proxy files from my local machine to this production machine, I cannot view them in ArcGIS Pro. It does recognize them as raster data and brings it to the location, but images are not visible.

I also recreated raster proxy files using the exact same settings as my local in my production environment, but it is still not visible. 

I opened one of the raster proxy files in notepad and noticed that it is pointing at /vsis3 as well as cachedSource path which was pointing to the old local path, I fixed the local path to the production cache path manually and confirmed that the cache file populates as I import the proxy file onto ArcGIS Pro.

Also, re-creating raster proxy with correct cache directory fixed the CachedSource path, but either method does not show the raster in Pro.

```
<MRF_META>
  <CachedSource>
    <Source>/vsis3/bucketname/foldername/0004737.04-Lindahl_Wind_Mosiac.170620.mrf</Source>
  </CachedSource>
  <Raster>
    <Size c="3" x="70225" y="110115"/>
    <PageSize c="3" x="512" y="512"/>
    <Compression>JPEG</Compression>
    <DataValues NoData="255"/>
  <DataFile>D:/drone_data/cache/0004737.04-Lindahl_Wind_Mosiac.170620.mrf_cache</DataFile><IndexFile>D:/drone_data/cache//0004737.04-Lindahl_Wind_Mosiac.170620.mrf_cache</IndexFile></Raster>
  <Rsets model="uniform" scale="3"/>
  <GeoTags>
    <BoundingBox maxx="1391581.50000000" maxy="593411.00000000" minx="1356469.00000000" miny="538353.50000000"/>
    <Projection>PROJCS["NAD83 / North Dakota North (ft)",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",48.73333333333333],PARAMETER["standard_parallel_2",47.43333333333333],PARAMETER["latitude_of_origin",47],PARAMETER["central_meridian",-100.5],PARAMETER["false_easting",1968503.937],PARAMETER["false_northing",0],UNIT["foot",0.3048,AUTHORITY["EPSG","9002"]],AXIS["X",EAST],AXIS["Y",NORTH],AUTHORITY["EPSG","2265"]]</Projection>
  </GeoTags>
</MRF_META>
```

I appreciate your input if there is something that I am missing from environmental variable or settings.

Best,
Shingo

**Comment by jdrisdelle** [comment]
I've never used optimize rasters @jgravois .  This is something that Peter and Abhijit from the solutions team manages.

**Comment by jgravois** [comment]
this is unfamiliar territory for me, but a colleague pointed out that its crucial that the cache directory be local on each ArcGIS Server machine. a network share is apparently a recipe for problems.

>  The raster proxy and cache directories are ... shared as data store in AGS

you mean you [registered a raster store](https://enterprise.arcgis.com/en/server/latest/publish-services/windows/registering-your-data-with-arcgis-server-using-manager.htm#ESRI_SECTION1_BF6287C0DD5B413D979055B627E49618), correct?

hopefully someone else with more experience can chime in too.

**Comment by abhiataero** [comment]
@shingike 
can you upgrade the version of ArcGIS Pro to 2.2 and try it out.

**Comment by shingike** [comment]
@jgravois 
Thank you for taking a look! This image workflow can chain multiple raster processings to optimize raster data to MRF format and create a mosaic dataset for ArcGIS Server to disseminate tiled images to the organization.  We are trying to optimize post processed UAV data and publish its mosaic dataset to AGS.

@abhiataero 
Thank you for the tip! Upgrading to 2.2.3 fixed the issue to display raster proxy. It seems neither ArcMap (10.6) and ArcGIS Pro (<2.2) has issues displaying raster proxy. I am now building Mosaic Dataset using the MDC.py script. I have about 140 raster proxy files with options for CM+AR+AF+BB+SP+CC+DO+BO+CV. It seems to stuck for +3 hours since it initiated the BO (Build Overview) process.

_Logistics Concern:_
We have several sets of UAV dataset for project locations and often repeated (time series) images. It may be better to optimize these images into a separate bucket folder and create and publish a separate mosaic dataset for each of them.  However, this approach defeats the purpose of the mosaic dataset since the goal here is to have a single mosaic dataset with time series capability.  Ideally, we create mosaic dataset (CM) once and keep adding a new set of raster proxy files and run BuildOverview (BO) + CalculateValue (CV) with expression like STARTTIME IS NULL. It would be good to have a document with best plactice examples.

**Comment by shingike** [comment]
Thanks for all for the suggestions and assistance to the optimize raster configurations. I will close this issue since any issue to the MDC.py should be discussed in its own repo.
