### ISSUE TITLE
When will we support Ali Yun?

### ISSUE THREAD

**Issue by yh371174229** [Esri/OptimizeRasters#81]
I am a Chinese user. I want to know if I will consider supporting cloud storage in China in the future, such as Aliyun and Tencent Cloud.

**Comment by Chamlika** [comment]
@yh371174229  Aliyun OSS is compatible with the Amazon S3 APIs. This means, OptimizeRasters has the necessary code added to read and write to Alibaba OSS. However this is not yet documented but I'll see to pass on the required information for you to test.

**Comment by yh371174229** [comment]
Thank you very much,hope to test it

**Comment by Chamlika** [comment]
@yh371174229 Few notes below,
I've updated the GitHub code, please pull before any tests. OptimizeRastes treats aliyun OSS as a S3 compatible cloud store. Installation of the OSS Python SDK is not required. 
Please follow the instructions below to connect with the Aliyun OSS/Alibaba,
Using the Profile Editor,
   a. Profile Type => Amazon S3
   b. Profile Name => User choice. 
   c. Access/Account Key ID => OSS ACCESS KEY ID
   d. Secret Access/Account Key => OSS SECRET ACCESS KEY
   e. Endpoint URL => User domain, e.g. http://oss-cn-shanghai.aliyuncs.com

This should create the required profile and will be saved in the %userprofile%/.aws/credential file.
This is the same file where the Amazon S3 credentials get saved. 
Once the profile has been created, you may use the OptimizeRasters Tool within ArcGIS Pro/ArcMap as usual to connect with the Aliyun OSS by selecting the input profile name created earlier using the 
Profile Editor. 

Note the followings for UI entries for the OptimizeRasters Tool,
Input Source => Amazon S3
Secured Bucket => Checked if the bucket is private else uncheck for public bucket access. 

If you use the Configuration File (CreateRasterProxy) to generate proxy files using a
Secured Bucket checked, the following environment variables need to be set at the system level for the 
ArcGIS Pro/ArcMap to connect/render the rasters properly,

OSS_ACCESS_KEY_ID=<access_key>
OSS_SECRET_ACCESS_KEY=<secret_key>

Let us know of any issues, thank you!
