### ISSUE TITLE
Is this project versioned?

### ISSUE THREAD

**Issue by robertd** [Esri/OptimizeRasters#83]
Hello,

We are about to include this project as a dependency for some of our MRF processing pipelines, but we cannot figure out if this project is versioned. There is no changelog.md, tags, releases or anything else other than v2.0.2 in the readme files. As we would include this repo as git submodule we're a bit reluctant that not having versions/tags we could bring in possible regressions as well. 

Thanks!

**Comment by Chamlika** [comment]
Presently with each GitHub push, the header information in each source file gets updated to reflect the last code update date and the new version number. Notes of any changes that include enhancements and/or bug fixes is added to the description text during each commit and push operation. Presently any pdates to OptimizeRasters is dynamic in nature and is not tied with any other release cycles.

**Comment by Chamlika** [comment]
@robertd There's a single release available now to reflect the branch master as of 20190304.  The project will be versioned to include any major updates in the future. Thanks!

**Comment by robertd** [comment]
@Chamlika Hey thanks. That helps a lot.
