### ISSUE TITLE
Raster Proxy black images 

### ISSUE THREAD

**Issue by kafisher36** [Esri/OptimizeRasters#85]
I am using the Optimize Rasters tool in ArcGIS Pro v2.3.0.  My end goal is to take my local tif images and create the image in S3 bucket, build a mosaic dataset from the raster proxy in the SDE and generate image service in Portal for ArcGIS.  I used the configuration file, Imagery_to_MKR_LERC and it ran without errors.  The images in the S3 bucket look good, however when adding the local raster proxy  to the map, it is black with no data.
Can I please have assistance in troubleshooting this or advice on a different workflow?

**Comment by lucianpls** [comment]
Sounds like a bucket access problem, from the client machine.

If the client application is an arcgis server, the arcgis user has to be able to access the bucket, and it needs write access to the cache folder location.

**Comment by kafisher36** [comment]
I have opened the bucket and the contents to public access and I still have the issue.  I also can add the S3 image to the map and view it.  It is just the local raster proxy that provides the black image.

**Comment by Petwet2000** [comment]
Did you set the S3 environment variables?

**Comment by Petwet2000** [comment]
The
[cid:image001.png@01D4F461.8E9F5A00]

From: Christopher Patterson
Sent: Tuesday, April 16, 2019 2:32 PM
To: Esri/OptimizeRasters <reply@reply.github.com>
Subject: RE: [Esri/OptimizeRasters] Raster Proxy black images (#85)

Did you set the S3 environment variables?

**Comment by kafisher36** [comment]
Yes, I set the environment variables to use the AWS credentials.

**Comment by Petwet2000** [comment]
- Are you using the latest build of OptimizeRaster from GitHub? 
- Can you tell me what the format of the images are? The format before apply Imagery_MRF_Lerc optimization. 
- Was it Tiff, JPG etc?
- Also are you able to share one of the (public) proxy files for review?

**Comment by kafisher36** [comment]
I am using OptimizeRaster v2.0.2 that I just downloaded at the beginning of April.  The images are Tiffs.  And yes, I have attached the local proxy file.  The raster is in a public S3.
[Downtown.zip](https://github.com/Esri/OptimizeRasters/files/3090256/Downtown.zip)

**Comment by Chamlika** [comment]
@kafisher36  Could you please check with the latest on GitHub. The version on GitHub is v2.0.4.  Thanks!

**Comment by kafisher36** [comment]
@Chamlika Could you please send me the download URL for 2.0.4?  I only see the 2.0.2 release from March 4, 2019.

**Comment by Chamlika** [comment]
@kafisher36 https://github.com/Esri/OptimizeRasters/raw/master/Setup/OptimizeRastersToolsSetup.exe

**Comment by kafisher36** [comment]
I reran it with the same outcome.

**Comment by Chamlika** [comment]
@kafisher36 Do you think you can give us the converted MRF source files (idx, lrc,mrf) that the proxy file is pointing at or if you could, the gdalinfo on the original raster before the conversion. Thanks!

**Comment by kafisher36** [comment]
Here is the URLs to the MRF source files:
https://s3-us-west-2.amazonaws.com/gistestrasterstorage2/Aerial2017/Downtown.idx
https://s3-us-west-2.amazonaws.com/gistestrasterstorage2/Aerial2017/Downtown.lrc
https://s3-us-west-2.amazonaws.com/gistestrasterstorage2/Aerial2017/Downtown.mrf

Thanks in advance for your help.

**Comment by Chamlika** [comment]
@kafisher36 Can you check if the attached raster proxy works for you? it looks like the aws region isn't included in the URL. Thanks!
[Downtown.zip](https://github.com/Esri/OptimizeRasters/files/3091150/Downtown.zip)

**Comment by kafisher36** [comment]
This works!  Can you explain how to add the aws region?

**Comment by Chamlika** [comment]
@kafisher36 OK. OptimizeRasters should reflect the AWS domain/region automatically in the raster proxy files unless it's the default which is us-east-1. I'm assuming here your processed data (lrc,idx,mrf) live in us-west-2 region. The hint was in the URLs to download the test files. This could be a potential bug in OptimizeRasters but I need to test when I get a chance to see if this is indeed the case.

**Comment by kafisher36** [comment]
@Chamlika Yes, they are in the us-west-2 region.

**Comment by Chamlika** [comment]
@kafisher36 I'd like to know how was the proxy file created, was it created automatically while the processed data was being uploaded to S3 using the -rasterproxypath or was it created separately in another session by using the CreateRasterProxy template giving the processed rasters on S3 as input? Thanks!

**Comment by Chamlika** [comment]
@kafisher36 The issue will require a fix in OptimizeRasters. According to Amazon, for some buckets that are outside of the default region (us-east-1), the region has to be explicitly set in the endpoint URL to avoid errors due to delays in DNS synchronization on their side. You'll be notified once fixed and tested. Thanks!

**Comment by kafisher36** [comment]
@Chamlika The proxy file was created automatically while using the Imagery_to_MKR_LERC configuration.  Thank you!

**Comment by Chamlika** [comment]
@kafisher36 Could you give it a try with the updated *OR source attached to see if the issue has been resolved. Have the original source from the *OR setup replaced with the attached, and close any ArcGIS/Pro sessions that may be open before any tests. Thanks!
[OptimizeRasters.zip](https://github.com/Esri/OptimizeRasters/files/3095198/OptimizeRasters.zip)

**Comment by kafisher36** [comment]
@Chamlika Unfortunately I still have the same results.  I double checked and the new .py file is in the toolbox and I closed and reopened Pro after adding the .py file and prior to running the tool.

**Comment by Chamlika** [comment]
@kafisher36 Could you pass me the newly generated proxy file? If you've ArcMap, could you check on that too. I'm beginning to think it could be a rendering issue here. Let's see. Thanks!

**Comment by kafisher36** [comment]
[Downtown.zip](https://github.com/Esri/OptimizeRasters/files/3095939/Downtown.zip)
@Chamlika Thanks for reviewing it.

**Comment by Chamlika** [comment]
@kafisher36 The updated source should've added the region into the proxy URL unless the output cloud region is the default  'us-east-1'. Could you pass me log files for the last run located at c:\Image_Mgmt_Workflows\OptimizeRasters\logs
Thanks!

**Comment by kafisher36** [comment]
@Chamlika Here is the log file.

[OR_20190418T103235666398_20190418T105158.zip](https://github.com/Esri/OptimizeRasters/files/3096064/OR_20190418T103235666398_20190418T105158.zip)

**Comment by Chamlika** [comment]
@kafisher36 
OK got it.
Let's do the followings,
1. Open up a DOS window and type in notepad %userprofile%/.aws/credentials
2. Search for the output profile 'kahenrik'
3. Remove the line 'aws_endpoint_url = https://s3.amazonaws.com'
4. Save the credentials file and rerun *OR to test.

Let me know, thanks

**Comment by kafisher36** [comment]
@Chamlika 

I did complete your above directions and rerun it but unfortunately I still get a black image.

**Comment by Petwet2000** [comment]
Chamlika,
The only way I was able to view the file you sent was to remove the "clone=’true’ statement in the proxy file. However it was slow to load. Maybe if "pyramids" value was set to ‘source’ while generating raster proxies if might improve performance. Don't know why but that was what worked for me.

**Comment by Petwet2000** [comment]
Updated proxy attached.
[Downtown_Updated.zip](https://github.com/Esri/OptimizeRasters/files/3096863/Downtown_Updated.zip)

**Comment by lucianpls** [comment]
The clone mode only works if the cache has exactly the same organization as the source, so that tiles can be copied over.  It has to match tile size and alignment, compression, data type, almost everything.
And indeed, if it doesn't match something it will break and ArcGIS will show black.
When it does match, it saves some time because it doesn't need to encode the cache tiles.  But it shouldn't be set when it's not appropriate.

I think a test script that catches the most common issues is needed.

**Comment by Chamlika** [comment]
@kafisher36 Could you check if your degenerated proxy file URL now shows (us-west-2)? Thanks!

**Comment by Chamlika** [comment]
@kafisher36 
OK, it looks like this is what has happened to you,
when you initially had this issue, the raster image returned was (black) and this was due to possible DNS issue on the Amazon side where some buckets may need the region in the request (URL) set to allow access. However the updated *OR code sent later explicitly sets the region that the output bucket was created in, in your case it's the  us-west-2.
But here is the problem, any subsequent tests done still points/fetches the cache off the cache folder C:/Aerial/mrfCacheTest2/ that still has the original error/black image.

Solution>
1. Close any running ArcGIS Pro/ArcMap sessions
2. Manually delete folder C:/Aerial/mrfCacheTest2/
3. Rerun ArcGIS Pro and load up the proxy file created with the updated *OR sent earlier. (There's no need to reprocess the dataset, you can reuse the same proxy file with the URL that should have the region us-west-2 included.

Let me know, Thanks!

**Comment by kafisher36** [comment]
@Chamlika This works!  Both the old proxy file and the new one that was sent work.  Thank you so much for your assistance!

**Comment by kafisher36** [comment]
@Chamlika Unfortunately all subsequent conversions using the Imagery to MRF LERC configuration are returning a black image.  Can you help me understand what is causing this?

**Comment by Chamlika** [comment]
@kafisher36 I suspect it's a region us-west-2 issue. Could you upload the exact dataset to another region like to a us-east-1 bucket and see if it's the same issue? Thanks!

**Comment by kafisher36** [comment]
@Chamlika I created a new bucket in N. Virginia and reran the tool.  Unfortunately the raster proxy returns a black image still.

**Comment by Chamlika** [comment]
@kafisher36 Do you think you could arrange us a sample raster to test this issue further. If not, could you do a gdalinfo on the original Tiff file and give us that information. Thanks!

**Comment by kafisher36** [comment]
@Chamlika It actually still happens on the image I was using prior as well as the other TIFFs. Here is the URL to the image.  https://s3-us-west-2.amazonaws.com/gistestrasterstorage2/TIFF/Downtown.tif

**Comment by Chamlika** [comment]
@kafisher36 I'm not able to download the raster 'download.tif', access-denied.

**Comment by abhiataero** [comment]
@kafisher36 can you share you emailid i can send you an meeting invite so we can do a screen share and take a look on what is really causing this.

**Comment by kafisher36** [comment]
@Chamlika I apologize for the access issue.  I've made it public now.

**Comment by kafisher36** [comment]
@abhiataero My email is karenfisher@asu.edu if you would still like to screenshare.

**Comment by Chamlika** [comment]
@kafisher36  I'm not able to reproduce the issue. This could be something new for us. @abhiataero will follow up with you with a screen share to find a possible solution. Thanks!
