### ISSUE TITLE
Ratser Proxy Caching

### ISSUE THREAD

**Issue by Petwet2000** [Esri/OptimizeRasters#86]
Hi,
With multiple (separate) image services running on the server, how do you turn proxy caching off for one service but not another? For example I would like to turn off MRF Caching for an elevation service that will be used for raster analysis but have caching enabled for imagery service to be used for visualization. 

Thanks,

**Comment by abhiataero** [comment]
@Petwet2000, if you dont need caching in that case directly use the url to add the data and do not use raster proxy
