### ISSUE TITLE
Blob to blob temp files cleardown

### ISSUE THREAD

**Issue by sandrews90208** [Esri/OptimizeRasters#90]
When were converting tif to mrf jpeg going from Azure blob to Azure blob, all input tifs are initially downloaded from source blob to the input temp folder. This is problematic when were processing hundreds of 800MB tiles as our local drives fills up very quickly. However when we run OR local to Azure blob, images are processed in small batches of 4 and the intermediate image is deleted from the output temp folder following upload to blob. Is there a way when processing blob to blob to process in small batches of tiles in the same way to avoid this buildup of downloaded rasters?

**Comment by Chamlika** [comment]
@sandrews90208 Can you remove the input arg -tempinput when you do the Azure blob to Azure Bob. With the -tempinput omitted, the source files will be addressed directly by OR rather than downloading the source files locally before the conversion takes place, thanks!
