### ISSUE TITLE
Support .rst raster format

### ISSUE THREAD

**Issue by slibby** [Esri/OptimizeRasters#94]
Am I missing something to get conversion working with .rst (Idrisi format) rasters? It seems to be supported by gdal: https://gdal.org/drivers/raster/Idrisi.html

I tried running OptimizeRasters with `Imagery_to_TIF_JPEG` and `Imagery_to_MRF_JPEG` and both failed to do any conversion. I had to add `'rst'` to `RasterFormatFilter` to get it to recognize the files, but it seems to fail for unknown reasons:

```
Running script OptimizeRasters...
log-msg:Copying non rasters/aux files (C:/temp/gaez/src/=>C:/temp/gaez/output/)..
log-msg:Done.
log-msg:Copying files to -tempinput path (C:/temp/gaez/tmp/)
log-msg:[CPY] C:/temp/gaez/tmp/alfa200a_cbd.rst
log-msg:[CPY] C:/temp/gaez/tmp/alfa200a_cyl.rst
log-msg:[CPY] C:/temp/gaez/tmp/alfa200a_eta.rst
log-msg:Converting..
log-msg:[Resume] Creating job (C:\Image_Mgmt_Workflows\OptimizeRasters\OR_20191007T170755973613.orjob)
log-msg:Copying non rasters/aux files (C:/temp/gaez/src/=>C:/temp/gaez/output/)..
log-msg:[CPY] alfa200a_cbd.RDC
log-msg:[CPY] alfa200a_cyl.RDC
log-msg:[CPY] alfa200a_eta.RDC
log-msg:Done.
log-msg:Converting..
log-msg:Removing input rasters at (C:/temp/gaez/tmp/)
log-msg:[Del] C:/temp/gaez/tmp/alfa200a_cbd.rst
log-msg:[Del] C:/temp/gaez/tmp/alfa200a_cyl.rst
log-msg:[Del] C:/temp/gaez/tmp/alfa200a_eta.rst
log-msg:Done.
log-msg:Done..
log-status:[Failed!]
Completed script OptimizeRasters...
```
![image](https://user-images.githubusercontent.com/1691225/66355627-27110780-e925-11e9-89c1-c06ddd7c87ce.png)

Note these images display fine in Pro if added manually. 

Pro 2.4.1, latest OptimizeRasters code.

Any ideas?

Sample Data here: https://esriis-my.sharepoint.com/:f:/g/personal/samu6308_esri_com/EoEu1zq_SdxFjL05i40JVxUBIzzOQ3Vb-9exC1N83LQCRg?e=39gz6M

**Comment by lucianpls** [comment]
@slibby 
Run gdalinfo on one of the input "rst" and post the output.

**Comment by slibby** [comment]
See below:
```
C:\Image_Mgmt_Workflows\OptimizeRasters\GDAL\bin>gdalinfo.exe  "C:\temp\gaez\src\alfa200a_cbd.rst"
Driver: RST/Idrisi Raster A.1
Files: C:\temp\gaez\src\alfa200a_cbd.rst
       C:\temp\gaez\src\alfa200a_cbd.rdc
Size is 4320, 2160
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
Origin = (-180.000000000000000,90.000000000000000)
Pixel Size = (0.083333333333333,-0.083333333333333)
Corner Coordinates:
Upper Left  (-180.0000000,  90.0000000)
Lower Left  (-180.0000000, -90.0000000)
Upper Right ( 180.0000000,  90.0000000)
Lower Right ( 180.0000000, -90.0000000)
Center      (   0.0000000,   0.0000000)
Band 1 Block=4320x1 Type=Int16, ColorInterp=Gray
  Min=0.000 Max=365.000
  NoData Value=-9
  Unit Type: undefined
```

**Comment by lucianpls** [comment]
@slibby 
Not sure if this is the full extent of the problem, but JPEG compression can't handle 16bit signed data.
You can try LERC, DEFLATE or LZW.

**Comment by slibby** [comment]
Seems to fail the same way when using Imagery_to_TIF_LZW or Overviews_to_MRF_LERC

**Comment by slibby** [comment]
I was able to translate it with `gdal_translate` successfully, so I think it's something in the Python, not an issue with GDAL, or so it seems to me:

![image](https://user-images.githubusercontent.com/1691225/66356541-8ae8ff80-e928-11e9-9ec3-23493301e92d.png)

**Comment by lucianpls** [comment]
That command only built a raw tif (uncompressed).  But yes, you might be right, I'm not that familiar with the OR python part.

**Comment by slibby** [comment]
`c:\temp\gaez\src>c:\Image_Mgmt_Workflows\OptimizeRasters\GDAL\bin\gdal_translate.exe -of MRF -co "COMPRESS=LERC" alfa200a_cbd.rst alfa200a_cbd.mrf
Input file size is 4320, 2160
0...10...20...30...40...50...60...70...80...90...100 - done.`

Also works exporting to compressed MRF (the output MRF works in Pro too).

**Comment by lucianpls** [comment]
@slibby 
RST seems to be a multi-file format, and the log says something about copying files to some temporary location.

There is a addRelatedExtensions(), called in OptimizeRasters.py, line 1571 and 1572
It takes two strings of semicolor separated extensions, first string has the main file extension, and the second one for secondary file extensions. 

Maybe adding this line at 1573 will help:
`
self._m_rasterAssociates.addRelatedExtensions('rst;RST', 'rdc;RDC;ref;REF;smp;SMP')
`

**Comment by abhiataero** [comment]
@slibby i modified the config file (Imagery_to_MRF_LERC.xml) to add the raster filter, 
<RasterFormatFilter>tif,tiff,TIF,TIFF,img,jp2,JP2,IMG,JPG,jpg,sid,SID,**rst,RST**</RasterFormatFilter>  
<ExcludeFilter>tmp,rrd,idx,lrc,mrf_cache,pjp,ppng,pft,pzp,ovr,aux.xml,aux,tfw,TFW,pjg,**RDC,rdc**</ExcludeFilter>

Used the below command "c:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\python.exe" c:\Image_Mgmt_Workflows\OptimizeRasters-master\OptimizeRasters.py -config=c:\Image_Mgmt_Workflows\OptimizeRasters-master\Templates\Imagery_to_MRF_LERC.xml -input=d:\data\rstdata\2020sH -output=d:\data\rstdata\2020sHmrf

it worked fine

Using the UI skip temporary Input Folder parameter ( leave it empty)

**Comment by abhiataero** [comment]
@slibby  did you get a chance to test it out
